### ISSUE TITLE
incremental build/watch tasks

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#129]
https://github.com/gulpjs/gulp#incremental-builds

**Comment by MathiasTim** [comment]
Can you provide more information on this issue? Sorry, I don't get whats the case here.

**Comment by gruppjo** [comment]
Sorry for the lack of information here. This allows gulp to only handle files that are actually changed in a watch or build cycle. This might improve performance a little bit in some cases.

**Comment by gruppjo** [comment]
Closing. Outdated.
