### ISSUE TITLE
tutorials/getting started guides

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#140]
- explain the technology stack for newbies (reuse existing resources on the web, don't repeat the web)
- explain how everything's working together, examine build etc.. in depth
- guide through basic usage scenarios
  - adding a new bower component. related #142 
  - updating a bower component/npm module yourself
- architecture recommendations?

**Comment by timoweiss** [comment]
:+1:

**Comment by LunarDevelopment** [comment]
:+1:

**Comment by gruppjo** [comment]
obsolete done with #157 respectively
