### ISSUE TITLE
device livereload

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#143]
- livereload for the device
- ionic lab (slide 18)
- ionic/angular superpowers
  - talk - https://www.youtube.com/playlist?list=PLOETEcp3DkCoNnlhE-7fovYvqwVPrRiY7
  - slides - http://adamdbradley.github.io/ionic-present/

**Comment by gruppjo** [comment]
Can we use `browsersync` for that as well? Might be worth migrating from `livereload` to `browsersync` http://www.browsersync.io/docs/api/

**Comment by MathiasTim** [comment]
Browsersync livereload on device via plugin: https://github.com/axemclion/cordova-plugin-browsersync.
