### ISSUE TITLE
Scss linting

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#179]
I dont know if it will be very useful, but I just found this:

https://github.com/brigade/scss-lint

**Comment by gruppjo** [comment]
I've been thinking about this recently. Good idea!

**Comment by MathiasTim** [comment]
More on this:

http://csscomb.com/ (is there a scss equivalent?!)
https://twitter.com/addyosmani/status/595354728894074880

**Comment by gruppjo** [comment]
https://github.com/juanfran/gulp-scss-lint requires ruby :(

**Comment by gruppjo** [comment]
https://github.com/sasstools/sass-lint :)

**Comment by gruppjo** [comment]
closing this as there is a more general and newer discussion here https://github.com/mwaylabs/generator-m-ionic/issues/284
