### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#181]
e.g. document pitfalls like:
https://gist.github.com/MathiasTim/d2f11f0f93344ebf2d72

**Comment by gruppjo** [comment]
troubleshooting. e.g. - https://github.com/mwaylabs/generator-m-ionic/wiki/Troubleshooting

**Comment by gruppjo** [comment]
es6, ionic2/angular2

**Comment by gruppjo** [comment]
Why not any other solution like ionic CLI, generator-cordova, generator-cordova-angular?

**Comment by gruppjo** [comment]
@MathiasTim, pitfalls like one you mentioned are be covered in the new docs.

**Comment by MathiasTim** [comment]
@lordgreg just posted in our company chat more useful snippets:

if you got more than one iOS-Versions

```gulp --cordova 'run ios --target="iPad-Air, 8.4"'
gulp --cordova 'run ios --target="iPad-Air, 9.0”’```

@gruppjo I couldn't find the new FAQ, If you tell me  where to put It I can do a PR as well.

**Comment by gruppjo** [comment]
Hi Mathias, the new docs are in the dev branch, since version 1.5 is not released yet. I'll just include it real quick.
