### ISSUE TITLE
handling translations better

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#190]
maybe we have to separate this from the generator, but I think we should discuss it anyway.

We have some tasks, that could be done by gulp:
- scan the project for unused translation keys
- diff translation files for differences/updates
- lint defined structure of translation files (json)
  - we need to define a structure as well I think

Before we start with this, we need to consider, that from the current [angular-translate](https://github.com/angular-translate/angular-translate) we could move to the new [core i18n](https://github.com/angular/i18n) package, since it should be released with 1.4.

**Comment by gruppjo** [comment]
@MathiasTim, is this still relevant?

**Comment by gruppjo** [comment]
closing, since the issue is outdated. Please feel free to comment, when you feel otherwise.
