### ISSUE TITLE
gulp watch - sometimes new files not injected in index.html

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#194]
Maybe related to https://github.com/gulpjs/gulp/issues/651
Which will also fix #146

I did some debugging and found out that the problem occurs when running the task `inject-all`. https://github.com/mwaylabs/generator-m/blob/master/app/templates/gulp_tasks/injecting.js#L16
Here's what happens:
1. This task runs the `wiredep` task as its dependency which also manipulates the `index.html`. 
2. Since `wiredep` is running first, it triggers the `changed` event on the `index.html` which results in a livereload. 
3. Apparently when the `inject-all` task runs itself after wiredep has finished, no new change event is triggered. 

Thus the `index.html` does contain the new file, but no livereload is performed and the new files is missing in the `index.html`.

I created a new issue with gulp https://github.com/gulpjs/gulp/issues/1074

**Comment by contra** [comment]
FYI we have a new file watcher in gulp 4.0 so this can be closed

**Comment by gruppjo** [comment]
closing, since the issue is outdated. Please feel free to comment, when you feel otherwise.
