### ISSUE TITLE
unexpected behaviour: gulp watch and gulp build at the same time

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#227]
Sometimes when running gulp watch and gulp build at the same time the `app/main/constants/config-const.js` is emptied.

**Comment by RomainGoncalves** [comment]
Ahhh is that why?! I was wondering why my const file was empty when I was running gulp build!

**Comment by MathiasTim** [comment]
yeah, thats why. Unfortunately we cannot reproduce this issue continuously. Can you? Thanks for your help!

**Comment by gruppjo** [comment]
today I encountered this error as well while running both of the tasks at the same time.
```sh
[18:13:05] 'clean' errored after 1.76 s
[18:13:05] Error: ENOTEMPTY: directory not empty, rmdir '/Users/jonathan/Projects/m-way/qr-code-test/.tmp/main/styles'
    at Error (native)
```

**Comment by MathiasTim** [comment]
+1 having this issue from time to time.

**Comment by gauravarora** [comment]
I have this problem too with the following versions
```
bash-3.2$ node -v
v4.2.1
bash-3.2$ npm -v
3.3.12
```

**Comment by gianko** [comment]
+1

Is there a way to "refill" the file?

Now I'm getting `angular.js:68 Uncaught Error: [$injector:unpr] Unknown provider: ConfigProvider <- Config ...`

**Comment by gruppjo** [comment]
We usually just use git and simply checkout the file.
` git checkout app/main/constants/config-const.js`

you can generate a new file with the sub-generator:
 `yo m-ionic:constant config --template=config`

**Comment by gruppjo** [comment]
Closing this one. Discussion moved the new collective ticket: https://github.com/mwaylabs/generator-m-ionic/issues/453
