### ISSUE TITLE
test integration with other gulp tasks

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#232]
How should the gulp tasks `karma` and `protractor` integrate with the other gulp tasks?

- should they be run, when running `gulp watch`? (not possible right now due lack of browsersync #228)
- own `karma-watch` tasks? since `gulp karma:auto` cannot be forced to do checks when files change, neither re-runs it when app files change.
- when they're run alone, should they perform style-checks etc? on which files?

**Comment by MathiasTim** [comment]
From my perspective we should be fine for now with having them separated from the other gulp tasks. I think we need some time to figure out how and when we will run the tests.
