### ISSUE TITLE
jade support

### ISSUE THREAD

**Issue by sibelius** [mwaylabs/generator-m-ionic#234]
it should have jade support, thanks

**Comment by gruppjo** [comment]
Please be more specific about your request and how you would like to see it implemented. Please be aware that we are currently not considering jade templating to be a priority. However if somebody would lay out a good suggestion for an implementation, we're happy to work with you and PRs.

For this purpose please also refer to our https://github.com/mwaylabs/generator-m/wiki/Contribution-Guide

**Comment by gruppjo** [comment]
Moved from gitter chat: @TristanWinters, I'm sure you already found the right plugin for this task: https://www.npmjs.com/package/gulp-jade
We don't have experience with Jade so I can only guess for now without further looking into it. Out of the top of my head there's a couple of places you'll need to touch though (not sure if complete, but I think it might be a somewhat big change):

1. when running `gulp watch` if I assume that it will be necessary to somehow template the files, move them to the `.tmp` folder (similar to what `gulp styles` is doing)
1. these files then need to be copied to the `www` folder when building: `gulp/building.js` see the `build-templates` task
2. the `karma.conf.js` will need to be adapted: search for `templates`

**Comment by gruppjo** [comment]
Requests like these should be integrated via recipes in the future: https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/contribute/faq.md#why-dont-you-support-x

**Comment by azachar** [comment]
Hi there!
I made the jade integration. Currently I am testing it, if you want feel free to look at it. 

https://github.com/mwaylabs/generator-m-ionic/compare/master...azachar:master

I have a question on you. Do you know why the clean command doens't work when I run ``gulp build-watch`` but when I run ``gulp clean`` it works..

Anyway I hope this would help to make jade fully supported.

**Comment by azachar** [comment]
Could you please reopen this issue so more people can provide with a feedback? My solution is stable enough, but it is just a sandbox and requires a review. For example I am not very happy with having a separate `tmp-jade` folder for jade compilations. Also watching function seems to me not working well, but I will post it into a separate issue.

**Comment by gruppjo** [comment]
Hi @azachar, thanks for your PR. It's very welcome :) I didn't have time to look at it yet, but will very soon!

**Comment by gruppjo** [comment]
I'm closing this. Since it's outdated. If you're still interested please let me know!
