### ISSUE TITLE
ES6 support with babel

### ISSUE THREAD

**Issue by TakayukiSakai** [mwaylabs/generator-m-ionic#237]
Why don't we support ES6 with [babel](https://babeljs.io/).

It seems to be not so difficult to integrate babel transpiler in gulp task thanks for gulp-babel plugin.
[This article](http://labs.encoded.io/2015/06/22/use-es6-with-ionic/) explains how we can automate transpilation process with gulp.

I really want to use bunch of libraries for ES6 like [co](https://github.com/tj/co) on ionic like on io.js.
How do you guys think about this? Do you want this feature too?

**Comment by gruppjo** [comment]
Hi @TakayukiSakai!
Thanks for your suggestion and the article. We've been thinking about ES6 support for quite a while. See #155. The only reason we haven't integrated it yet is that we always had higher-priority features that we wanted to integrate first, so ES6 support hasn't made it into any of the milestones yet.
It will come eventually.

However if you want to speed things up and have some time to spare we'd be happy to discuss implementation details with you for a PR.

**Comment by gruppjo** [comment]
Requests like these should be integrated via recipes in the future: https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/contribute/faq.md#why-dont-you-support-x
