### ISSUE TITLE
more recipes

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#240]
## More recipes
- ESLint: mention the different eslintrc files, eslintignore
- Generator update
  - keep a list of changes to generator files (preferably in readme with link to commit)
  - rename old project folder
  - create new empty folder with project name
  - create new project (yo m-ionic) with options from old project
  - git init git commit
  - copy app folder, config.xml, res folder, test folder and other files that you changed
  - git diff
  - ...
  - npm bower cordova install
- copy docs to project?
- How to configure your editor to work with the linting rules provided by the generator

I wrote on another issue:

> `index.html`
> 
> ```
> <meta name="format-detection" content="telephone=no"> 
> ```
> 
> `config.xml`
> 
> ```
> 
> <preference name="KeyboardDisplayRequiresUserAction" value="false" />
> 
> <preference name="DisallowOverscroll" value="true" />
> <preference name="webviewbounce" value="false" />
> ```

@MathiasTim wrote in another issue:

> the other stuff can be added to the config.xml into the ios section like this:
> 
> ```
> <platform name="ios">
>   
>   <preference name="DisallowOverscroll" value="true" />
>   <preference name="webviewbounce" value="false" />
> </platform>
> ```
> 
> The focus part is not needed anymore I think because this is only an issue when developing for iOS7.
> Since the [Market Share](https://developer.apple.com/support/app-store/) of iOS7 dropped to 13% and is likely to fall when iOS9 will be released in the next months.

**Comment by gruppjo** [comment]
funny I found this, since I just opened #218 one month ago with similar thoughts ;)

the other stuff can be added to the config.xml into the ios section like this:

```
<platform name="ios">
  <!-- prevent ionic modal container from being scrolled -->
  <preference name="DisallowOverscroll" value="true" />
  <preference name="webviewbounce" value="false" />
</platform>
```

The focus part is not needed anymore I think because this is only an issue when developing for iOS7.
Since the [Market Share](https://developer.apple.com/support/app-store/) of iOS7 dropped to 13% and is likely to fall when iOS9 will be released in the next months.

**Comment by gruppjo** [comment]
`index.html`
```
<meta name="format-detection" content="telephone=no"> <!-- no auto telephone linking -->
```
`config.xml`
```
<!-- allow to set focus from js -->
<preference name="KeyboardDisplayRequiresUserAction" value="false" />
<!-- prevent ionic modal container from being scrolled -->
<preference name="DisallowOverscroll" value="true" />
<preference name="webviewbounce" value="false" />
```

**Comment by mathias** [comment]
I think you mean @mathiasbynens ;)

**Comment by gruppjo** [comment]
Woops, sorry. Corrected! ;)

**Comment by mathiasbynens** [comment]
Nope, I never said anything like that. Must be some other Mathias :)

**Comment by mathias** [comment]
Sounds like we need to make a `mathiases` org to resolve these things ;)

**Comment by gruppjo** [comment]
I meant my colleague @MathiasTim. Usually he pop ups first when I type `mathias`. Not this time obviously ;)

**Comment by MathiasTim** [comment]
So finally you got the right person, *me* :D

**Comment by gruppjo** [comment]
outdated.
