### ISSUE TITLE
gulp: source maps not working with imported files

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#243]
@MathiasTim 
>
Sorry, but still don't seem to work for imported files (```_filename.scss```).
<img width="738" alt="screen shot 2015-09-05 at 13 39 07" src="https://cloud.githubusercontent.com/assets/1793379/9699072/c0e24720-53d3-11e5-9b90-b9e6df2b7748.png">
<img width="266" alt="screen shot 2015-09-05 at 13 39 00" src="https://cloud.githubusercontent.com/assets/1793379/9699074/c4b9cbe8-53d3-11e5-835f-fc4c41d1f112.png">
<img width="249" alt="screen shot 2015-09-05 at 13 39 13" src="https://cloud.githubusercontent.com/assets/1793379/9699075/c72f44c0-53d3-11e5-8b36-21a42c100674.png">

**Comment by gruppjo** [comment]
https://gist.github.com/DrMabuse23/97f038bf1c25572bdf4e

**Comment by MathiasTim** [comment]
any progress here?

I'm asking because we are doing a large project right now and it could be nice having working source maps :)

**Comment by gruppjo** [comment]
With the help of @DrMabuse23's script, I was able to reduce this to this simplest, viable use case. Tested with latest version of canary and chrome:
 ```js
gulp.task('styles', ['clean'], function () {

  // compile css starting from each module's scss
  return gulp.src('app/*/styles/!(_)*.scss')
    .pipe($.plumber())
    .pipe($.sourcemaps.init())
    .pipe($.sass.sync().on('error', $.sass.logError))
    .pipe($.sourcemaps.write())
    .pipe($.autoprefixer({ browsers: ['last 2 versions'], remove: false}))
    .pipe(gulp.dest('.tmp/'));
});
