### ISSUE TITLE
Add support of ripple emulator

### ISSUE THREAD

**Issue by srouaix** [mwaylabs/generator-m-ionic#248]
It will be very interesting to integrate ripple-emulator http://ripple.incubator.apache.org/

If we install ripple-emulator manually, it doesn't work correctly -> error after some seconds.

ripple permit to test like it was a device without push apk on a an emulator or a device (steps very slow)

**Comment by gruppjo** [comment]
Hi @srouaix, thanks for bringing this up. 
I personally have no experience using ripple. Integration doesn't seem difficult, so I'm generally open to it. @MathiasTim what do you think? Has anyone of the team used it yet? Would be great to have some experiences.

**Comment by gruppjo** [comment]
Actually I can't get it to run... https://github.com/apache/incubator-ripple
How did you run it?

when I install it and run `ripple emulate --path ./www`
![image](https://cloud.githubusercontent.com/assets/1370779/9792359/11102810-57e0-11e5-80bc-7f643585e76c.png)
![image](https://cloud.githubusercontent.com/assets/1370779/9792375/2253ced8-57e0-11e5-8e46-d8d35140a329.png)

Also it says it detects cordova 3 project which just is utterly wrong. It should be 5.2.0

**Comment by gauravarora** [comment]
@gruppjo this might be of help - https://github.com/diegonetto/generator-ionic/blob/master/templates/common/_Gruntfile.js#L447-L475

**Comment by gauravarora** [comment]
FWIW the emulator works with `ripple emulate --path <absolute path>` on my mac.

**Comment by gruppjo** [comment]
Requests like these should be integrated via recipes in the future: https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/contribute/faq.md#why-dont-you-support-x
