### ISSUE TITLE
Travis install command not updated for Cordova 5.x yet

### ISSUE THREAD

**Issue by diagramatics** [mwaylabs/generator-m-ionic#260]
Found out you guys updated the `gulp cordova-install` command to use `cordova prepare`, but the Travis install command hasn't been updated yet. [This one specifically](https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/.travis.yml#L4).

**Comment by gruppjo** [comment]
You are absolutely right. Thanks!
