### ISSUE TITLE
Protractor error with gulp

### ISSUE THREAD

**Issue by skyfitz79** [mwaylabs/generator-m-ionic#262]
**After creating a project, everything is fine (yo generators, gulp tasks included gulp karma).** 

**I've created a test into "test/protractor" and the execution is fine by using** protractor protractor.conf.js :

>Finished in 1.818 seconds
>1 test, 1 assertion, 0 failures
>Shutting down selenium standalone server.
>[launcher] 0 instance(s) of WebDriver still running
>[launcher] chrome #1 passed

**but with** gulp protractor **it give me the following error (pattern file pb)**

>C:\__TEMP\yeoman-m-ionic>gulp protractor
>[23:13:34] Using gulpfile C:\__TEMP\yeoman-m-ionic\gulpfile.js
>[23:13:34] Starting 'clean'...
>[23:13:34] Starting 'wiredep'...
>[23:13:34] Starting 'bower-fonts'...
>[23:13:34] Starting 'environment'...
>[23:13:34] Starting 'eslint'...
>[23:13:35] Starting 'jsonlint'...
>[23:13:35] Starting 'webdriver-update'...
>[23:13:35] gulp-inject 1 files into main\constants\config-const.js.
>[23:13:35] Finished 'wiredep' after 1.53 s
>[23:13:35] Finished 'jsonlint' after 614 ms
>selenium standalone is up to date.
>chromedriver is up to date.
>[23:13:35] Finished 'environment' after 1.49 s
>[23:13:35] Starting 'build-vars'...
>[23:13:35] Finished 'webdriver-update' after 543 ms
>[23:13:35] Finished 'clean' after 1.65 s
>[23:13:35] Starting 'styles'...
>[23:13:36] gulp-inject 1 files into main\constants\config-const.js.
>[23:13:39] Finished 'build-vars' after 3.57 s
>[23:13:39] Finished 'eslint' after 4.98 s
>[23:13:39] Starting 'linting'...
>[23:13:39] Finished 'linting' after 13 μs
>[23:13:39] Finished 'bower-fonts' after 5.23 s
>[23:13:39] Finished 'styles' after 3.61 s
>[23:13:39] Starting 'inject-all'...
>[23:13:39] gulp-inject 5 files into index.html.
>[23:13:39] gulp-inject 1 files into index.html.
>[23:13:39] Finished 'inject-all' after 215 ms
>[23:13:39] Starting 'serve'...
>[23:13:39] Finished 'serve' after 12 ms
>[23:13:39] Starting 'protractor'...
>WARNING - pattern C:\__TEMP\yeoman-m-ionic\test\protractor\main.js did not match any files.
>[launcher] Process exited with error code 1
>C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\node_modules\q\q.js:126
>                    throw e;
>                          ^
>Error: Spec patterns did not match any files.
>    at Runner.run (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\lib\runner.js:249:11)
>    at TaskRunner.run (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\lib\taskRunner.js:123:19)
>    at createNextTaskRunner (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\lib\launcher.js:223:20)
>    at C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\lib\launcher.js:246:7
>    at _fulfilled (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\node_modules\q\q.js:797:54)
>    at self.promiseDispatch.done (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\node_modules\q\q.js:826:30)
>    at Promise.promise.promiseDispatch (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\node_modules\q\q.js:759:13)
>    at C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\node_modules\q\q.js:573:44
>    at flush (C:\__TEMP\yeoman-m-ionic\node_modules\gulp->protractor\node_modules\protractor\node_modules\q\q.js:108:17)
>    at process._tickCallback (node.js:355:11)

>C:\__TEMP\yeoman-m-ionic\gulp\testing.js:42
      throw err;
            ^
>Error: protractor exited with code 1

**Comment by gruppjo** [comment]
Hi @skyfitz79, this is odd... the `gulp protractor` task just includes all the files in `test/protractor/` and runs their tests. See https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/gulpfile.js#L15.
I'm confused because the error says that it doesn't find a certain `protractor\main.js` which should be covered by the glob pattern above and anyhow, how does protractor know about that file when it's not there?

How does your filestructure look in `protractor/`?

**Comment by gruppjo** [comment]
closed due to inactivity
