### ISSUE TITLE
error when running the generator for the first time (empty directory)

### ISSUE THREAD

**Issue by neslinesli93** [mwaylabs/generator-m-ionic#264]
Hi, I'm using node v4.1.1 and npm v3.3.5.
I tried following the basic intructions on the README and, after installing yo, gulp and bower I run
`yo m-ionic` and I get the following error:
`Couldn't finish generator: 
CordovaError: Could not find directory: /usr/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/cordova-app-hello-world`

I tried to move the generator's peerDependency of `"yo": ">=1.0.0"` inside the dependencies, since npm from version 3 will complain about peer dependencies. Then I tried to change cordova version from 5.2.0 to 5.3.3, but I still get the error

**Comment by neslinesli93** [comment]
The problem was npm version: the provided tutorial works for version 2 and is currently broken for version 3.
You can close this issue

**Comment by gruppjo** [comment]
Hi @neslinesli93, thanks for pointing out how you got it to work!

**Comment by gruppjo** [comment]
For updates on this issue please, follow the issue I just referenced
