### ISSUE TITLE
Be aware that project generator-m-ionic-demo uses Ionic CSS and not SASS

### ISSUE THREAD

**Issue by lordgreg** [mwaylabs/generator-m-ionic#265]
This isn't a bug, just a reminder or a notice to other developers, if they're using [Generator-M-Ionic-Demo](https://github.com/mwaylabs/generator-m-ionic-demo) project as empty starter kit, they should be aware that the version `1.3.2` that is the latest version there, uses Ionic CSS and not SASS. 

This means, if you're updating your project with demo files, please be aware of correct paths. Your old SASS project uses `main/assets/fonts/` to store ionic fonts and Ionic CSS uses `font/` directory directly. Meaning, you won't be able to see any icons if upgrading. To fix this problem, just read and resolve things discussed in [Ionic CSS or SASS guide](https://github.com/mwaylabs/generator-m-ionic/blob/4f924563b8a98c8c7285456aac5fcedadc8af35a/docs/guides/ionic_css_or_sass.md).

**Comment by gruppjo** [comment]
Maybe it's a good idea to mention the default options in the Demo Readme. Thanks for pointing this out.
