### ISSUE TITLE
Improvement: Microsoft TACO Support

### ISSUE THREAD

**Issue by volkrass** [mwaylabs/generator-m-ionic#266]
Microsoft TACO provide a tool (https://github.com/Microsoft/TACO) to help Windows Developer to Setup Cordova correctly. Could be helpful to setup generator-m-ionic much more easy on a Windows box.

**Comment by gruppjo** [comment]
Sounds interesting. Would like to have the opinion of somebody who has worked with it. Anyone?

**Comment by volkrass** [comment]
It is brand new, so I guess we will not find a lot people surrounding of us with experience on this. Let it open for somebody else who is interested too.

**Comment by gruppjo** [comment]
I'm closing this, since it's not of any relevance right now. Ok? If not, just reopen.

Requests like these should be integrated via recipes in the future: https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/contribute/faq.md#why-dont-you-support-x
