### ISSUE TITLE
Immediately-invoked function expressions

### ISSUE THREAD

**Issue by LimeBlast** [mwaylabs/generator-m-ionic#268]
I'm sorry if this is a silly question, or the wrong place for such a question, but can I ask:

Why don't your code generators use Immediately-invoked function expressions?

I'm very new to (serious) JavaScript development, so figured I'd throw myself in the deep end and do some Ionic. I've found this generator and like what you're doing with it, but you seem to be adopting standards unfamiliar to what I've been learning, such as [IIFEs](https://github.com/johnpapa/angular-styleguide#iife), [Anonymous Functions](https://github.com/johnpapa/angular-styleguide#named-vs-anonymous-functions), and [more](https://github.com/johnpapa/angular-styleguide).

Thank you.

**Comment by MathiasTim** [comment]
Hey @LimeBlast! This is definitely not a silly question :)

All patterns you describe are recommendations by John Papa, which is a great guy, but we do not agree on all his ideas. There is nothing wrong with it, its just not our 'style'.
This is why we are generating files using our own structure and style. We will maybe change this in the future, but for now its not in our scope.

If you have any other questions, do not hesitate to ask, but maybe the gitter-chat (https://gitter.im/mwaylabs/generator-m-ionic) is a better place.

**Comment by LimeBlast** [comment]
Thank you very much for your answer. I'll pop along to your gitter and ask the rest of my silly questions there :+1:
