### ISSUE TITLE
Generator not installing cordova-lib dependencies...

### ISSUE THREAD

**Issue by yoooee** [mwaylabs/generator-m-ionic#270]
To get the generator to work after the initial installation, I had to go to the following directory and run npm install.

npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/

**Comment by gruppjo** [comment]
Hi @yoooee, I tried to reproduce with a fresh install using `npm install --global generator-m-ionic` and it ran without any problems. The `cordova-lib` is listed as a regular dependecy https://github.com/mwaylabs/generator-m-ionic/blob/master/package.json#L51 so I assume there was a problem with npm or your internet connection?

Can you verify this with a fresh install?

**Comment by yoooee** [comment]
Thanks for the response gruppjo.

Upon doing a fresh install of the generator, I receive the following:

npm WARN engine xmlbuilder@2.2.1: wanted: {"node":"0.8.x || 0.10.x"} (current: {"node":"4.1.2","npm":"3.3.6"})
npm WARN install:convert-source-map ENOENT: no such file or directory, rename '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/insert-module-globals/node_modules/convert-source-map' -> '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/gulp-sourcemaps/node_modules/convert-source-map'
npm WARN install:readable-stream ENOENT: no such file or directory, rename '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/npm/node_modules/sha/node_modules/readable-stream' -> '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/gulp-sourcemaps/node_modules/readable-stream'
npm WARN install:isstream ENOENT: no such file or directory, rename '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/isstream' -> '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/isstream'
npm WARN install:readable-stream ENOENT: no such file or directory, rename '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/bl/node_modules/readable-stream' -> '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/readable-stream'
npm WARN install:readable-stream ENOENT: no such file or directory, rename '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/npm/node_modules/npm-registry-client/node_modules/concat-stream/node_modules/readable-stream' -> '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream'
npm WARN install:readable-stream ENOENT: no such file or directory, rename '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/npm/node_modules/request/node_modules/bl/node_modules/readable-stream' -> '$HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/vinyl-fs/node_modules/merge-stream/node_modules/readable-stream'
...
 Other out put of installation
...

npm WARN EPEERINVALID generator-m-ionic@1.3.4 requires a peer of yo@>=1.0.0 but none was installed.
npm ERR! code 1

Then upon running the yo m-ionic command, I receive the following error:
Couldn't finish generator:
CordovaError: Could not find directory: $HOME/.npm-packages/lib/node_modules/generator-m-ionic/node_modules/cordova-lib/node_modules/cordova-app-hello-world

Thanks

**Comment by gruppjo** [comment]
Looks like a problem with npm... what version of npm are you using? Maybe @MathiasTim has an idea what going on?

**Comment by yoooee** [comment]
I'm using npm 3.3.6

**Comment by gruppjo** [comment]
There's more people having issues with npm 3. I suggest downgrading npm until we figure out why there's issues with that...
https://github.com/mwaylabs/generator-m-ionic/issues/257
https://github.com/mwaylabs/generator-m-ionic/issues/264

**Comment by gruppjo** [comment]
For updates on this issue please, follow the issue I just referenced
