### ISSUE TITLE
roadmap 1.4

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#273]
- ~~documentation / blog article 2~~
- ~~npm issues~~
- ~~maintenance / community~~
- issues cleanup (feature stop)

**Comment by MathiasTim** [comment]
maybe upgrade libsass (speed improvements) ? https://twitter.com/nodesass/status/657753410880602114

**Comment by gmarziou** [comment]
Would you consider Typescript as in [this Ionic demo](https://github.com/ksachdeva/ngCordova-typescript-demo)?

**Comment by gruppjo** [comment]
@MathiasTim, libsass/node-sass update should be covered by our regular dependency updates
@gmarziou, we've been discussing transpilers for a while now, but for now it's not a priority. We want to wait how everything with Angular 2. Ionic 2 and ES6 plays out.
For the time being if anyone wants to publish a guide how to integrate typescript support on a per project basis, we're happy to accept pull-requests.

**Comment by gruppjo** [comment]
the libsass update is automatically since the version bump in gulp-sass to the latest node-sass version is a minor version update.
The results are awesome, roughly twice as fast :)
![image](https://cloud.githubusercontent.com/assets/1370779/10907851/e37439aa-822d-11e5-85f9-744482a71909.png)

**Comment by gruppjo** [comment]
@gmarziou, more info on typescript and the whole angular 2 discussion: https://github.com/mwaylabs/generator-m-ionic/blob/dev/docs/contribute/faq.md#what-about-angular-2-ionic-2-es6-babel-and-typescript

**Comment by gmarziou** [comment]
Thanks, I have started learning Typescript with Angular 1.x as I think that learning it at same time as Angular 2 will be a much higher step. If you add Ionic 2 to this picture, I think it's worth doing baby steps :)

**Comment by gruppjo** [comment]
Yes! We're discussion how we'll transition here: https://github.com/mwaylabs/generator-m-ionic/issues/294 feel free to join!
