### ISSUE TITLE
travis - add integration tests: protractor, karma, ...

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#278]
see : https://travis-ci.org/Swiip/generator-gulp-angular/jobs/88423802 and https://github.com/Swiip/generator-gulp-angular/blob/master/.travis.yml
- include in travis tests
- include in gulp watch tests (and possibly other tasks)
- adapt gulpfile to match generator-generator recommendations - https://github.com/yeoman/generator-generator/releases/tag/v1.0.0

this we could test:
- debug page
- proper injecting/watching/building, bootstrapping, localforage and other components, ...
- eslint/jsonlint files after generation, watching etc...

**Comment by gruppjo** [comment]
The hardest part is getting protractor to run in travis. I did some digging around for options:
- [sauce labs](https://saucelabs.com/home) is an alternative for running selenium (and free for open source projects) 
- [chrome is available](http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/#comment-2627309228) in the [travis trusty beta](https://docs.travis-ci.com/user/trusty-ci-environment/)
- other resources
  - http://blog.500tech.com/setting-up-travis-ci-to-run-tests-on-latest-google-chrome-version/
  - https://github.com/travis-ci/travis-ci/issues/272#issuecomment-194348354

**Comment by paralin** [comment]
@gruppjo Did you ever figure this out?

**Comment by gruppjo** [comment]
@paralin, no, not yet unfortunately. Did you?

**Comment by gruppjo** [comment]
Closing this, because the only thing that isn't working is running protractor on travis and details are discussed over here: https://github.com/mwaylabs/generator-m-ionic/issues/487
