### ISSUE TITLE
new eslint rules

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#279]
I just found out, that semicolons are no longer necessary in all places with the new  linting (`eslint`)

Example:

```
var foo = 'bar'
```
This is valid for eslint, until you add to your `.eslintrc` Eslint Rule: [semi](http://eslint.org/docs/rules/semi#options)
```
"semi": [2, "always"]
```
maybe there is a better way, but for now this works for me.

I think we should add this to the next version.
Maybe there are other rules we missed in the first place, I'll ask the team if they found anything.

**Comment by gruppjo** [comment]
yes, let me know!

**Comment by gruppjo** [comment]
please reopen if persists
