### ISSUE TITLE
Appium for tests on real devices

### ISSUE THREAD

**Issue by hoegertn** [mwaylabs/generator-m-ionic#286]
Hi,

did you consider using Appium for end-to-end tests on real devices? It is also possible to use Appium for AWS DeviceFarm to test your app on many real devices in the cloud.

I will try to create a sample setup.

http://appium.io/
https://aws.amazon.com/de/device-farm/

**Comment by gruppjo** [comment]
Sounds awesome! We'll definitely look into it.

**Comment by gruppjo** [comment]
I still like the idea, but I'm closing this issue as it is definitely out of scope for this generator.
