### ISSUE TITLE
New Technology Stack: Angular 2, Ionic 2, ...

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#294]
This issue should serve as a platform for discussions on the new technology stack
## What technologies will we use?
- [angular 2](https://github.com/angular/angular)
- [ionic 2](https://github.com/driftyco/ionic2)
  - http://ionicframework.com/blog/angular-2-ionic/
- es6 and possibly: babel and typescript
  - http://kangax.github.io/compat-table/es6/
  - http://angularjs.blogspot.de/2015/09/angular-2-survey-results.html
  - http://blogs.msdn.com/b/typescript/archive/2015/03/05/angular-2-0-built-on-typescript.aspx
## How do we transition?
- http://angularjs.blogspot.de/2015/12/angular-2-beta.html (samples/demos)
- #312 TypeScript support
## Research
- playground repo for and comparison
- generator-ionic updates - https://github.com/diegonetto/generator-ionic
- generator ionic2 gulp webpack - https://github.com/DrMabuse23/generator-ionic-2
- ionic(2) cli
- angular cli
- angular2 generator
## How will the old generator be available when we switch to the new technology stack?
- when and how do we switch?
- will we maintain the old stack?
- generator-m-1x or compose generator-m-cordova to port generator-m-1x and generator-m to newer cordova versions at the same time?

**Comment by volkrass** [comment]
I would suppose to keep generator-m-ionic 1.x as our Angular 1.x/Ionic 1.x maintenance stream.

**Comment by gruppjo** [comment]
One more opinion: https://github.com/mwaylabs/generator-m-ionic/issues/273#issuecomment-166311136

**Comment by volkrass** [comment]
Like the idea to consider typscript in combination with Ionic 1 and Angular 1. It reduces the learning curve  and helps to migrate ideas from our existing angular 1 apps to angular 2.

**Comment by gmarziou** [comment]
I agree, it seems also that Angular 1 will stay for long time, don't know what are the plans of Ionic team for Ionic 1.

**Comment by gruppjo** [comment]
`Ionic 1.2` was just release with a ton of new features. I'm pretty sure they realize that Angular 2 / Ionic 2 will need a while to be finished and get adapted. http://blog.ionic.io/announcing-ionic-1-2/

**Comment by NicholasGlazer** [comment]
@gruppjo 
If you want to be on top of the technologies, it sounds like a really good idea. And I hope you will change this stack soon. I'm looking forward to touch this new stack. You can maintain this one with stable version or even create a new rep with presenting technologies.
And what about structure best practices in new generator? #289

**Comment by qwerfrewq** [comment]
angular2, ionic2, gulp, webpack / npm (instead of bower) is the dream team i think.

**Comment by volkrass** [comment]
We would like to understand better what your thoughts are if there is a need to transform existing projects based on ionic1/angular1 to ionic2/angular2 or would it better to start with a 'fresh' setup and port only what you would like to save.

**Comment by gruppjo** [comment]
closing this as the discussion moved to #403. Please add any comments over there.
