### ISSUE TITLE
eslint updates according to yeoman

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#297]
yeoman uses the following `.eslintrc` rules: https://github.com/yeoman/generator/blob/master/.eslintrc. Should we adapt? We're pretty much in sync, although there's a lot of new ones. I think they're really useful and allow to capture nasty bugs and quirks before they happen. Differences are:
**additional rules**
- http://eslint.org/docs/rules/array-bracket-spacing
- http://eslint.org/docs/rules/brace-style
- http://eslint.org/docs/rules/consistent-return
- http://eslint.org/docs/rules/one-var
- http://eslint.org/docs/rules/quote-props
- http://eslint.org/docs/rules/space-in-parens
- http://eslint.org/docs/rules/no-eval
- http://eslint.org/docs/rules/no-with
- http://eslint.org/docs/rules/dot-notation
- http://eslint.org/docs/rules/no-alert
- http://eslint.org/docs/rules/no-caller
- http://eslint.org/docs/rules/no-empty-label
- http://eslint.org/docs/rules/no-extend-native
- http://eslint.org/docs/rules/no-extra-bind
- http://eslint.org/docs/rules/no-implied-eval
- http://eslint.org/docs/rules/no-iterator
- http://eslint.org/docs/rules/no-label-var
- http://eslint.org/docs/rules/no-labels
- http://eslint.org/docs/rules/no-lone-blocks
- http://eslint.org/docs/rules/no-loop-func
- http://eslint.org/docs/rules/no-multi-spaces
- http://eslint.org/docs/rules/no-native-reassign

**slightly different**
- http://eslint.org/docs/rules/space-before-function-paren
- http://eslint.org/docs/rules/eqeqeq

**Comment by MathiasTim** [comment]
I'm not quite sure, more rules can be better, but can also be a bit	annoying sometimes.
Some seem just logic to adopt, but not all.

We could end up disabling many rules for single lines.
Do you think all rules are necessary?

**Comment by gruppjo** [comment]
Don't think that's necessary right now.
