### ISSUE TITLE
ionic 1.2 update adjustments

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#298]
blog article - http://blog.ionic.io/announcing-ionic-1-2/
- template adjustments, label?
- remove ngCordova? add Ionic Native?
- more todos?

**Comment by MathiasTim** [comment]
I'd only replace `ngCordova` and update the generator to `Ionic 1.2` if we got first experiences with these changes.

What do you think?

**Comment by gruppjo** [comment]
My thoughts!
I think we can deliver Ionic 1.2 right now, since there's no breaking changes we have to account for. That way we can start experimenting with Ionic 1.2 but still can rely on ngCordova and such until we switch to Ionic Native. With our release of 1.6 we could then make further adjustments we deem useful like replacing ngCordova.

**Comment by gruppjo** [comment]
I'm closing this because I don't see any further adjustments to make in regards to ionic 1.2
