### ISSUE TITLE
`gulp protractor` task never returns

### ISSUE THREAD

**Issue by yossi-shasho** [mwaylabs/generator-m-ionic#310]
after done running the tests, `gulp protractor` process just hangs and never return. This makes it harder to run it in CI environments.

**Comment by gruppjo** [comment]
Hi @yossi-shasho, thanks for bringing it up. We are aware of this. We're planning to make improvements to the whole testing workflow #307.
Are you actively going to run it in CI environments? Some more perspectives than our own might be very helpful :)

**Comment by yossi-shasho** [comment]
@gruppjo yes, thats exactly what we're going to do - put it as one of the steps in our CI. I'd love to help you anyway i could.

**Comment by gruppjo** [comment]
The plugin we're currently using doesn't support this. I created an issue: https://github.com/mllrsohn/gulp-protractor/issues/94
However there's another plugin that does support this, but I think it doesn't handle the webdriver automatically, but I'll have to verify. https://github.com/rochejul/gulp-angular-protractor

**Comment by gruppjo** [comment]
They do support automatic webdriver download, but there is a different error: https://github.com/rochejul/gulp-angular-protractor/issues/8

**Comment by gruppjo** [comment]
This is how I ran it:
```sh
npm i --save-dev gulp-angular-protractor
```
In `gulp/testing.js`:
```js
gulp.task('protractor-new', ['serve', 'linting'], function (done) {
  gulp
    .src(paths.protractor)
    .pipe($.angularProtractor({
      'configFile': 'protractor.conf.js',
      'debug': false,
      'autoStartStopServer': true
    }))
    .on('error', function (e) {
      console.log(e);
    })
    .on('end', function () {
      bs.exit();
      done();
    });
});
```

When downgrading to `0.0.6` it ran fine, but the gulp task didn't stop after execution.

@yossi-shasho can you verify?

**Comment by yossi-shasho** [comment]
I followed the steps, however
`$ gulp protractor-new` never returned as well.


--
Learn easy card tricks: http://www.learncards.net

**Comment by gruppjo** [comment]
Ok, we'll just have to wait and see how this issue plays out:) mllrsohn/gulp-protractor#94 Maybe when can contribute to a solution. I'll be gone until Feb 29, so don't expect updates from me till then.

**Comment by gruppjo** [comment]
Hi all and @yossi-shasho, I traced this back to an issue in `browser-sync` (https://github.com/BrowserSync/browser-sync/issues/1121 and https://github.com/BrowserSync/browser-sync/issues/1052) and prepared a fix. This will work with the next version.
Additionally you can replay the changes from this commit (https://github.com/mwaylabs/generator-m-ionic/commit/4797546b9456e1ccf2524c1d24fa79e14da79fce) in your project and it should also work. Given that you have browser-sync `2.13.0` installed.

**Comment by yossi-shasho** [comment]
awesome! when will this be released?

**Comment by gruppjo** [comment]
No more than two weeks I think (depending on which features will make it into `1.9.0`). However it's fairly easy to produce in your current project as I mentioned above!
