### ISSUE TITLE
when running with xcode, app files are not up-to-date

### ISSUE THREAD

**Issue by yossi-shasho** [mwaylabs/generator-m-ionic#311]
scenario:
1. run app via xcode
2. create a change in the app code
3. build and run again
App remains without the change.

This was an issue with ionic generator too back in the day, but was fixed.

**Comment by gruppjo** [comment]
Hi @yossi-shasho,
cordova requires you to run `cordova prepare` after a `gulp build`. The prepare copies the the contents of `www/` into the `platform/` folders so you can run it with xCode for instance. Perhaps a section in the docs would be helpful for that.

**Comment by yossi-shasho** [comment]
thanks! however, why not incorporate it as a build step in the xcode project?

**Comment by gruppjo** [comment]
@yossi-shasho, I'm not that familiar with Xcode, how would you do that? - I can mention it in the docs, however I have some concerns.

We had bad experiences in the past with editing the xcode project. When you collaborate with other people via git or want to update to a new platform version, all these changes are lost can only be manually reproduced, as they're not part of the git repository. In our last blog article about the generator I explained what kind of problems we ran in when 1) cordova platforms and plugins were part of the git project and 2) how annoying it can be if you edit the xcode project that is generated by cordova. So if you are interested give it a look: http://blog.mwaysolutions.com/2015/09/21/generator-m-ionic-and-the-search-for-the-holy-grail/.

So for the scenario you are describing I think it's just the easiest and least error-prone if you just run the following after you make changes:
```sh
gulp --cordova 'prepare'
```
And then run via Xcode.

Does that make sense to you?

**Comment by yossi-shasho** [comment]
The motivation for using xcode in the first place is speed: when running with xcode, the time it takes the app to build, load and start on the phone is much shorter than when using the cordova CLI.
So, yes, your solution works and makes sense, but is less comfortable in situations in which you need to run your app many times on the phone or simulator in a row, for e.g. to do fine graphic adjustments.

**Comment by gruppjo** [comment]
That's perfectly true. As I said. If you point me towards a resource that explains how to set it up as a build setup, I'd be happy to include it in the docs, so everybody can handle it according to their own taste :)

**Comment by gruppjo** [comment]
I hope it's ok if I'm closing this for now. I mentioned the topic in the docs that will be released with the next version of the generator.
If you reply, I will still get back to you!
