### ISSUE TITLE
files dependent on angular-socket-io (socketFactory) / Socket.io client

### ISSUE THREAD

**Issue by MT--** [mwaylabs/generator-m-ionic#313]
Not sure how/where to put this:

I was running into the "io not defined" (pretty common for Socket.io) issue during the linting phase of this Gulp workflow. After trying all the suggestions from around the web to no avail, I just added the files that use this to .eslintignore just to get it to build, and it worked. I also fidgeted with the way Bower was loading the files just to be sure they were in the correct order.

##### Has anyone had this problem? Or am I just incompetent... :)

**Comment by gruppjo** [comment]
Hi @MT-- I have never worked with https://github.com/btford/angular-socket-io, so I can't help you with anything concerning that package, but you seem to have a problem with linting, right?
Just post the command line output here and I can see if I can help.

**Comment by MT--** [comment]
`gulp watch
[15:35:30] Using gulpfile ~/projects/lalali/gulpfile.js
[15:35:30] Starting 'clean'...
[15:35:30] Starting 'wiredep'...
[15:35:30] Starting 'bower-fonts'...
[15:35:30] Starting 'environment'...
[15:35:30] gulp-inject 1 files into main/constants/config-const.js.
[15:35:30] Finished 'wiredep' after 150 ms
[15:35:30] Finished 'environment' after 101 ms
[15:35:30] Starting 'build-vars'...
[15:35:30] gulp-inject 1 files into main/constants/config-const.js.
[15:35:30] Finished 'build-vars' after 14 ms
[15:35:30] Finished 'clean' after 188 ms
[15:35:30] Starting 'styles'...
[15:35:32] Finished 'styles' after 1.53 s
[15:35:32] Finished 'bower-fonts' after 1.71 s
[15:35:32] Starting 'inject-all'...
[15:35:32] gulp-inject 13 files into index.html.
[15:35:32] gulp-inject 1 files into index.html.
[15:35:32] Finished 'inject-all' after 161 ms
[15:35:32] Starting 'watch'...
[15:35:32] Starting 'eslint'...
[15:35:32] Starting 'jsonlint'...
[15:35:32] Finished 'watch' after 348 ms
[BS] Access URLs:
 --------------------------------------
       Local: http://localhost:3000
    External: http://192.168.0.195:3000
 --------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.0.195:3001
 --------------------------------------
[BS] Serving files from: app
[BS] Serving files from: .tmp
[15:35:33] Finished 'jsonlint' after 582 ms
[15:35:33] 
app/main/services/signal-svc.js
  8:17  error  "io" is not defined  no-undef

✖ 1 problem (1 error, 0 warnings)

[15:35:33] Finished 'eslint' after 1.25 s
[15:35:33] Starting 'linting'...
[15:35:33] Finished 'linting' after 12 μs
`

**Comment by MT--** [comment]
`
<script src="cordova.js"></script>



<script src="bower_components/socket-io-client/socket.io.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-animate/angular-animate.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
<script src="bower_components/ionic/release/js/ionic.js"></script>
<script src="bower_components/ionic/release/js/ionic-angular.js"></script>
<script src="bower_components/angular-socket-io/socket.js"></script>
<script src="bower_components/ngCordova/dist/ng-cordova.js"></script>
<script src="bower_components/localforage/dist/localforage.js"></script>





<script src="main/main.js"></script>
<script src="main/services/user-svc.js"></script>
<script src="main/services/signal-svc.js"></script>
<script src="main/services/record-svc.js"></script>
<script src="main/services/main-svc.js"></script>
<script src="main/services/call-svc.js"></script>
<script src="main/controllers/user-ctrl.js"></script>
<script src="main/controllers/record-ctrl.js"></script>
<script src="main/controllers/menu-ctrl.js"></script>
<script src="main/controllers/home-ctrl.js"></script>
<script src="main/controllers/debug-ctrl.js"></script>
<script src="main/constants/config-const.js"></script>
<script src="app.js"></script>

`

**Comment by MT--** [comment]
<script src="cordova.js"></script>

<script src="bower_components/socket-io-client/socket.io.js"></script>
<script src="bower_components/angular/angular.js"></script>
<script src="bower_components/angular-animate/angular-animate.js"></script>
<script src="bower_components/angular-sanitize/angular-sanitize.js"></script>
<script src="bower_components/angular-ui-router/release/angular-ui-router.js"></script>
<script src="bower_components/ionic/release/js/ionic.js"></script>
<script src="bower_components/ionic/release/js/ionic-angular.js"></script>
<script src="bower_components/angular-socket-io/socket.js"></script>
<script src="bower_components/ngCordova/dist/ng-cordova.js"></script>
<script src="bower_components/localforage/dist/localforage.js"></script>

<script src="main/main.js"></script>
<script src="main/services/user-svc.js"></script>
<script src="main/services/signal-svc.js"></script>
<script src="main/services/record-svc.js"></script>
<script src="main/services/main-svc.js"></script>
<script src="main/services/call-svc.js"></script>
<script src="main/controllers/user-ctrl.js"></script>
<script src="main/controllers/record-ctrl.js"></script>
<script src="main/controllers/menu-ctrl.js"></script>
<script src="main/controllers/home-ctrl.js"></script>
<script src="main/controllers/debug-ctrl.js"></script>
<script src="main/constants/config-const.js"></script>
<script src="app.js"></script>

**Comment by MT--** [comment]
If I add the file that depends on **angular-socket-io** to _.eslintignore_, Gulp tasks run just fine, and the app builds and run on Android with the expected WebSocket functionality with no problems.

**Comment by MT--** [comment]
If I had to guess, the variables aren't exposed until after the app is running, so linting would fail every time? @gruppjo

**Comment by gruppjo** [comment]
Try adding:
```js
  // ...
  "globals": {
     "io": true
     // ...
   },
   // ..
}
```
to your `app/.eslintrc` :)

**Comment by MT--** [comment]
Perfect! Thank you, linting and I have never gotten along!
