### ISSUE TITLE
Manual angular bootstrapping to avoid device ready issues

### ISSUE THREAD

**Issue by azachar** [mwaylabs/generator-m-ionic#318]
Hi there, 

I suggest that manually bootstrapping of angular will be done out-of-box. 

The motivation is simple: This will prevent some issues caused by not ready deviceready for some 3rd party libraries that are not ready yet, but angular is ready. Also this approach is not invasive and helps transform web app into mobile app faster.

**Comment by gruppjo** [comment]
Hi @azachar, I get what you mean, but I don't think it's a good idea. The way it's done now, you can hide the angular bootstrapping behind the splashscreen, which is neat. The problem you're describing with cordova plugins that are used through ngCordova or through direct plugin-API calls before `"deviceready"` should be safely avoided by wrapping the code in `ionic.Platform.ready()`. There is an example in the `DebugCtrl` of the Generator Demo: https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/app/main/controllers/debug-ctrl.js#L13-L15

**Comment by azachar** [comment]
Hello @gruppjo, 

Thank you for your response. Actually there were some projects that were totally incompatible with this approach. I tried to use a library angular-opentok that depends on the opentok cordova plugin, because the angular library angular-opentok was not aware of any delays with initialization of opentok sdk, i had a hard time to make it work. In other words I let the angular starts after the initialization of opentok sdk and then the angular 3rd party library for opentok was working ok. 

I guess most people won't have any issue with it, but since this is a generator and provides the best practices, there should be an option to let you initialize angular yourself.

Cheers,
Andrej

**Comment by gruppjo** [comment]
That's a good point. I think it would be easier and reduce maintenance for the generator if we provide it as a recipe or guide. To me it feels like a very advanced feature/option that will overwhelm beginners, whereas advanced developers will probably like to make adjustments based on their project requirements themselves. What do you think? 
Somewhat similar to this: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/bower_component_usage.md.

**Comment by gruppjo** [comment]
Closing this for now. Let me know if you're still interested.

**Comment by mikemichaelis** [comment]
This needs to be reopened and addressed - or updated.  I'm new to Ionic but not new to development.  This seems very wrong that the app framework (angular) is executing before the native components are even available.  I'm doing something as simple as using Auth0 to login.  I was very happy to see there is IonicStorage.  Unfortunately you can see from my boot log below, all my angular code is completely worthless until Storage is open.  There is no easy way to pause angular from starting up until after platform.ready().   I search and find this year old discussion where it's been decided not to address it. 

So, somebody please be kind enough to explain the proper way to wait for Cordova to be ready to use before Angular starts to inject services that are not ready.

The answer I have found is to manually inject the angular app after platform.ready() has been fired.  I think the OP had a great idea to do this out of the box, or another great idea already posted was to write a guild on how to do it.

Thanks,
Mike

Angular is running in the development mode. Call enableProdMode() to enable the production mode.
base.auth.service.ts:23 profile:      undefined
base.auth.service.ts:24 idToken:      undefined
base.auth.service.ts:25 accessToken:  undefined
base.auth.service.ts:26 refreshToken: undefined
SQLitePlugin.js:175 OPEN database: _ionicstorage
SQLitePlugin.js:106 new transaction is waiting for open operation
SQLitePlugin.js:106 new transaction is waiting for open operation
SQLitePlugin.js:179 OPEN database: _ionicstorage - OK
SQLitePlugin.js:80 DB opened: _ionicstorage
bootstrap.js:10 Ionic Native: deviceready event fired after 1320 ms 
app.component.ts:42 platform ready()
