### ISSUE TITLE
Ionic Deploy doesn't work because cordova.js is missing when building the deploy package.

### ISSUE THREAD

**Issue by yossi-shasho** [mwaylabs/generator-m-ionic#322]
My app uses [ionic deploy](http://docs.ionic.io/docs/deploy-from-scratch) for hot code pushes.
When it loads, it checks, downloads and deploys code updates.
In the new folder structure of generator-m-ionic, this stopped working. after a deploy is installed, the app becomes a white screen with js errors about missing cordova.js file.

The reason for the failure. is that ionic deploy wraps the `www` folder from the root folder into an update, but this folder doesn't contain the files `cordova.js` and `cordova_plugins.js`, which are present in the `platforms/*/www` folders.
In ionic's generated folder structure, these files are present in `./www`, so there are no problems.

A possible solution is to make sure these files are copied to `./www` folder in the `gulp --cordova 'prepare'` gulp task.

**Comment by gruppjo** [comment]
Hi @yossi-shasho, are you using the Ionic CLI with this generator? That's not what this generator is designed for. We do all our code deployment with Cordova and through our continuous integration services.

**Comment by yossi-shasho** [comment]
I'm specifically referring to ionic's "ionic deploy" feature, that enables hot code pushes to your app

**Comment by gruppjo** [comment]
You're right. It's a valid point, thank you very much for bringing it up. I'll discuss with the team. This might take a while as this affects our general strategy towards support for Ionic CLI and other Ionic tools. Due to the fundamental character of this topic I don't want to make rash, uneducated decisions rather a sound and precise one :)

**Comment by gruppjo** [comment]
hi @yossi-shasho, I'm closing this issue, since I created a new one for the platform command integration into the generator and I would like to hold any further discussions over there. Fine with you?

**Comment by yossi-shasho** [comment]
sure. any estimation regarding this integration?

**Comment by gruppjo** [comment]
I'll start this or next week. But then everything's possible. Might be a no-brainer or maybe it will take some complex adjustments or even PRs to the Ionic CLI, so not sure...

**Comment by gitChirag** [comment]
Hi gruppjo. Any update on above? I am facing the same issue. Did you figure the solution out yossi-shasho.

**Comment by gruppjo** [comment]
@gitChirag: you should find everything regarding the Ionic Platform integration in the Ionic Platform Integration Guide: https://github.com/mwaylabs/generator-m-ionic#ecosystems

**Comment by tilowr** [comment]
i'm having the same problem, any solution?

**Comment by MathiasTim** [comment]
Hey @tilowr :)
Did you read our guide about ionic: https://github.com/mwaylabs/generator-m-ionic#ecosystems ?
