### ISSUE TITLE
Bower not injecting dependency into index.html

### ISSUE THREAD

**Issue by izaakhaliq** [mwaylabs/generator-m-ionic#330]
I am trying to install 'pdfmake'. Ran 'bower install pdfmake --save-dev' but it didn't inject the path into index.html. Also ran 'gulp inject-all', 'gulp build-all -clean -inject-all', and 'gulp wiredep' to no avail. Is there no other way than to add the path manually into the index.html or did I miss something?

**Comment by MathiasTim** [comment]
Hey, normally you should install it just with `bower install --save`. After that the inject method looks in the `bower.json` of the component for the `main` attribute and injects it into your `index.html`.

If this will not work, you can inject it manually between the two following tags.

```
<!-- build:js scripts/vendor.js -->
<!-- bower:js -->
...
<!-- endinject -->
**inject your script here**
<!-- endbuild -->
```

Hope I could help you, let me know if it worked.

**Comment by izaakhaliq** [comment]
Wow, i don't know why it didn't happen previously. Maybe I missed something. Thanks @MathiasTim
