### ISSUE TITLE
New bower components not detected

### ISSUE THREAD

**Issue by izaakhaliq** [mwaylabs/generator-m-ionic#331]
I just added a few 3rd party components using bower install ... and also inject works where the source is linked in the index.html. 

But when i ran 'gulp watch', it seems those components are still not 'registered' because 'Cannot GET /bower_components/pdfjs-dist/build/pdf.js'. 

Am i missing a crucial step here?

**Comment by MathiasTim** [comment]
mhh it does not look like you missed anything.

Lets try to find the isse, here are some questions:

Are the components installed to the correct directory? should be `app/bower_components/`
Or did you change the `.bowerrc` file in the root of your project?
Did you compare file path to the injected path in `index.html` ?

**Comment by izaakhaliq** [comment]
I found out why..it's because my bowerrc has the wrong path. Thanks for trying to help me @MathiasTim .
