### ISSUE TITLE
Fix angular module generation

### ISSUE THREAD

**Issue by matheuscas** [mwaylabs/generator-m-ionic#334]
When I use the pair generator, it creates a module without dependencies, like this:

`angular.module('module_name')`

But this generates the following error

`Error: [$injector:nomod] Module 'module_name' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.`

To fix this, the module should be like this:

`angular.module('module_name', [])`

**Comment by gruppjo** [comment]
Hi @matheuscas, the pair generator does not create a new module. That is done with the `yo m-ionic:module` subgenerator. The pair generator merely creates a controller and a template pair in a given module.

So to create a module with a controller and template pair run:
```sh
# first create module
yo m-ionic:module myModule
# create pair
yo m-ionic:pair myModule
```

the `angular.module('module_name')` line is merely a getter.

I hope I could help. If not, please feel free to reopen :)

**Comment by matheuscas** [comment]
So, I think you guys have to change docs, perhaps. In [Quick Start](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/intro/quick_start.md) you tell that I can do something like this:
```
yo m-ionic:<component> <name> <moduleName>
```

So I did it: 
```
yo m-ionic:pair myList myModule
```

And it generated a template, an controller inside the *new* module, like it should do. But the module generation still produces an error. Whats the point of uses a generator and still have to fix it's generation? You know what I mean?

**Comment by gruppjo** [comment]
Maybe it might be less confusing to make this more obvious in the quick start guide. #335 What do you think?

**Comment by matheuscas** [comment]
Like a said, I think you guys should improve documentation, because even the latest link, did not reached what I pointed. To Explain that part what you said to me would be clarifying to the public. Thanks for the answers and keep the great job.
