### ISSUE TITLE
gulp --cordova 'run android'

### ISSUE THREAD

**Issue by PeaceDeveloper** [mwaylabs/generator-m-ionic#339]
the command above launch:
Task 'android' is not in your gulpfile.

I'm using windows 10.

**Comment by corentin-gautier** [comment]
use " not ' on windows

**Comment by gruppjo** [comment]
@corentin-gautier is right. It's documented here: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/windows.md
