### ISSUE TITLE
Ionic io

### ISSUE THREAD

**Issue by kevin-sennoun-needone** [mwaylabs/generator-m-ionic#345]
Hi, 

Does it support ionic io ? I'm currently not able to use Ionic object after doing 

`ionic io init`

=> Ionic is undefined

**Comment by MathiasTim** [comment]
hey,

sorry right now the generator does not support the ionic commands.
We are thinking about a way to integrate it in the future, but we are nut sure how and if this could work.

**Comment by kevin-sennoun-needone** [comment]
Ok thanks for fast answer. Is there a way to use Ionic io services with the generator ? (push, user, deploy etc.)

**Comment by MathiasTim** [comment]
you can maybe try to integrate the ionic-specific config inside your project. (must be something like `ionic.config.json`)
Or you can ask in our [gitter-chat](https://gitter.im/mwaylabs/generator-m-ionic), I know other guides tried to solved it as well and asked there some questions, maybe they can help you.

**Comment by kevin-sennoun-needone** [comment]
Ok thank you I'll check that !

**Comment by gruppjo** [comment]
Hey @kevin-sennoun-needone. I'm curious. Did you get it to run? If so, this could serve as a blueprint for our integration efforts :)

**Comment by kevin-sennoun-needone** [comment]
I'm sorry I was quite in a rush and didn't take time to try. I went with default Ionic project for this time. I'll let you know if I give it a try.

**Comment by gruppjo** [comment]
No worries, I'm closing this issue, since I created a new one for the platform command integration into the generator. We can discuss everything over there in case you're still interested alright?
