### ISSUE TITLE
Error with Gulp tasks

### ISSUE THREAD

**Issue by PetruMagdeleine** [mwaylabs/generator-m-ionic#348]
Hello,

I generated the project using a normal workflow of generator-m-ionic. I selected sass, android as platform and blank as ionic template.

Using the followings inside the project folder :
$ npm install
$ bower install
$ gulp --cordova 'prepare' 

It shows :
...
[17:02:51] Finished 'resources' after 2.41 s
[17:02:53] Plumber found unhandled error:
 Error in plugin 'gulp-autoprefixer'
Message:
    "/bower_components/ionic/scss/ionic.scss" is not in the SourceMap.
Details:
    fileName: ... /app/main/styles/main.css
Stack:
Error: "/bower_components/ionic/scss/ionic.scss" is not in the SourceMap.

**Comment by gruppjo** [comment]
Hi @PetruMagdeleine, sorry you ran into troubles!
I just took the steps you described to reproduce this error and for me on MacOSX it ran without any problems.

My first guess is to delete the `node_module` and `app/bower_components/` folder and run `npm install` and `bower install` again to see if that problem persists.

**Comment by PetruMagdeleine** [comment]
Hi @gruppjo , thanks for help !

I deleted the `node_module` and `app/bower_components` folders. Run `npm install`, `bower install` and `gulp --cordova 'prepare'` ends with same result as above.

Using : 
npm:3.8.5,
bower:1.7.9,
yo:1.7.0,
gulp@3.9.1 

---

I re-run again the full Quick Start to be sure :
`npm i -g yo gulp bower`,
`npm i -g generator-m-ionic`,
`mkdir testProject && cd $_`,
`yo m-ionic`,
name: testing, bundleid: com.testing.app, choice sass, deactivate localforage, deactivate ios, selecting all cordova plugins, choice blank template, deactivate Appmobi
`gulp watch`

I get the same error.

**Comment by gruppjo** [comment]
Are you on Mac as well? From your node version I infer that you have node > 5.0 running is that correct?

Can you make your repo available for me through Github?

**Comment by PetruMagdeleine** [comment]
Yes : https://github.com/PetruMagdeleine/crashing-test

On Mac (10.11.3) but my node was v4.2.1.
I tried `n stable` upgrading my node to v5.10.1, then rerun install process but same error.

**Comment by gruppjo** [comment]
Hi @PetruMagdeleine thanks for making your repo available.
I cloned your repo and ran `npm install` `bower install` and then `gulp --cordova 'prepare'` and `gulp watch` without any errors...

At this point I'm not sure what to do...
As this seems like a random problem with gulp-autoprefixer and gulp-sourcemaps you might try disabling one of those and thus isolating the problem.

**Comment by PetruMagdeleine** [comment]
Hi @gruppjo,

Hum ...you're right, it was a silly mistake, many thanks for support !

I solved it by : 
`rm -rf bower_components`
`bower cache clean`
`bower install`

**Comment by gruppjo** [comment]
Wonderful! Thanks for letting me know how you solved this :)
Related #350
