### ISSUE TITLE
Gulp watch

### ISSUE THREAD

**Issue by dinoDuvnjak** [mwaylabs/generator-m-ionic#349]
It was impossible for me to change main.css file, every time it would produce an error in console, and couldn't load main.css again.

Also gulp would displayed a message saying that I have changed my constants .config file, although I didn't changed it.

**Comment by fmendoza** [comment]
Same here. Any solution?

**Comment by gruppjo** [comment]
I will need a lot more information on your problem and especially the error that you run in to, as well as a repository that I can clone that will produce this error, with a detailed description on how to reproduce this.

**Comment by dinoDuvnjak** [comment]
I just downloaded this repo, put some class into main.css file to test it, and saved file. On reload main main.css could not be loaded, only ionic.sccs files where included.

**Comment by gruppjo** [comment]
You'll need to be a bit more collaborative here so I can help you. There's many things that could go wrong.
- did you run `yo m-ionic` or did you clone the demo repository?
- which options did you choose during setup?
- which os and version are you on?
- which version of node/npm/yo/gulp are you running?
- what's the error in the console?

**Comment by diegoalmesp** [comment]
Hello! I have the same error here, I checked console permission (I'm on windows) but happends every time I save any scss file.
First, it runs the build several times, and then crash:
```
[13:04:22] Starting 'styles'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: must start with number, buffer, array or string
    at fromObject (buffer.js:167:9)
    at new Buffer (buffer.js:58:10)
    at DestroyableTransform._transform (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\wiredep\wiredep.js:136:23)
    at DestroyableTransform.Transform._read (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\wiredep\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\wiredep\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\wiredep\node_modules\readable-stream\lib\_stream_writable.js:313:64)
    at writeOrBuffer (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\wiredep\node_modules\readable-stream\lib\_stream_writable.js:302:5)
    at DestroyableTransform.Writable.write (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\wiredep\node_modules\readable-stream\lib\_stream_writable.js:241:11)
    at write (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:623:24)
    at flow (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:664:5)
    at emitNone (events.js:67:13)
    at DestroyableTransform.emit (events.js:166:7)
    at emitReadable_ (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:448:10)
    at emitReadable (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:444:5)
    at readableAddChunk (D:\DevTools\xampp\htdocs\Puertas_Mag\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:187:9)
```

Thanks!

**Comment by gruppjo** [comment]
Hi @diegoalmesp, I'm not able to test on windows so there's not much I can do. The problem probably lies with one of the node modules in combination with windows.

I'd google for the error messages and see if you find something similar also I'd clone the [demo repository](https://github.com/mwaylabs/generator-m-ionic-demo) and see if you run into the same problem.

Please report back with any findings, so other can benefit as well :)

**Comment by durasj** [comment]
Hey, same problem here. It disappers when gulp watch is started again.

Let me know what else I can do for you. Would really like to see this solved. I will continue to look for problem.

**Comment by cherylhanlon** [comment]
Hey, just reporting in that I have the same issue.  Created a clean project, ran yo m-ionic.  Picked sidebar, included everything, picked Sass options.  As soon as I modify the main.scss, it deletes the main.css from .tmp\main\styles and doesn't recreate it. 

This happens on my existing project, and a clean project just built.

Is there any information i can provide to help you guys pinpoint the issue?

**Comment by gruppjo** [comment]
Hi everyone, are you all working on windows?

For everything else please refer to our [Issue Guidelines](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/contribute/issue_guide.md) and I'm especially interested in your system setup (OS & version, node, npm, gulp, ...). Find the full list and information on how to obtain them in the guide.

**Comment by cherylhanlon** [comment]
Hello,

I will try be more helpful this time :D This is the steps I took and the versions I am using

Before I did any of these steps, I ran npm cache clean and bower cache clean.

I created a brand new app running yo m-ionic in an empty directory.  

* Picked Ionic SASS
* Included all bower packages
* Included IOS and Android
* Selected all Cordova plugins
* Side Menu Starter Template
* Added Ionic Platform ecosystem only

I run gulp watch

Whilst gulp watch is running I then I modified the main.scss (just changed a colour) and the CSS all disappears.  The main.css is deleted from the .tmp\main\styles and not recreated.  If I kill gulp watch and run it again, the CSS is generated.  This only happens if main.scss is modified when gulp watch is running.

 Versions
OS : Win 7 Professional - Service Pack 1
Node: v5.5.0
NPM: v3.9.0
M-Ionic : 1.8.0
Cordova: 6.1.1

Is there anything else I can provide?

Thanks

**Comment by durasj** [comment]
Exacly same steps, enviroment and problem expect for OS. Running Windows 10 Pro, all latest updates.

**Comment by gruppjo** [comment]
Thank you @durasj and @cherylhanlon! 
The error output is the same as for @diegoalmesp?

Windows issues are hard for me to work on since I don't have a windows machine available. 

You can try to fix it yourself by playing around with the clean task: https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/gulp/building.js#L24-L28
Maybe this has to do with this commit? https://github.com/mwaylabs/generator-m-ionic/commit/c7551ab8a40a3da9e4573249f094b43ee291576c What happens if you revert the changes?
What happens when you remove the clean tasks as a dependency to the styles task? https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/gulp/injecting.js#L36

**Comment by cherylhanlon** [comment]
If I remove the clean task  dependency from styles, it works fine.  Thanks for that.

I assume the only negative impact of this would be if I deleted a scss file, it wouldn't be removed from the tmp folder or from injected includes lines (see below) until gulp watch is ran again?

```
<!-- inject:css -->
<link rel="stylesheet" href="main/styles/main.css">
<link rel="stylesheet" href="main/styles/mydeleted.css">
<!-- endinject -->
```

**Comment by diegoalmesp** [comment]
@gruppjo sorry I didn't answer before! if I re-start **gulp watch** everything works fine, the problem occurs every time I save any scss file. My problem seems to be the same as @cherylhanlon . For now I'm not using **watch** while doing scss.

**Comment by gruppjo** [comment]
@diegoalmesp, thanks for the information
@cherylhanlon, have you tried reverting this commit? https://github.com/mwaylabs/generator-m-ionic/commit/c7551ab8a40a3da9e4573249f094b43ee291576c thus replacing the current clean task with this one?
```js
gulp.task('clean', function () {
  return gulp.src(['.tmp', paths.dist + '/*'])
     .pipe(vinylPaths(del));
});
```

**Comment by cherylhanlon** [comment]
If I leave the clean task dependency in and revert the commit, when I modify the scss file i get the following error

```
[BS] Serving files from: app
[BS] Serving files from: .tmp
[14:15:59] Starting 'clean'...
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: watch null EPERM
    at exports._errnoException (util.js:856:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1296:21)```

**Comment by fmendoza** [comment]
I'm using a Mac and I have this error too. Previous version works good.

**Comment by gruppjo** [comment]
This might be a solution. Can anyone test? https://github.com/mwaylabs/generator-m-ionic/issues/317#issuecomment-222931884
