### ISSUE TITLE
bower: invalid meta, name

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#353]
With the latest version of bower `1.7.9` the `bower.json` of the demo might produce this error.
```sh
bower invalid-meta  The "name" is recommended to be lowercase, can contain digits, dots, dashes
```

Ensure valid meta name by adhering to guidelines.

**Comment by nod** [comment]
Any workarounds for this discovered?

**Comment by gruppjo** [comment]
open your `bower.json` and change the `"name"` property to be all lowercase and without spaces:
So this:
```js
"name": "My Project",
```
Should be turned into
```js
"name": "my-project",
```
Or something of the sort.

I will update the generator later to automatically generate a compatible name.

Please not that when you run `bower install` this error might also be thrown by some of the bower packages you use.

**Comment by nod** [comment]
Thanks!  This seems to have fixed it.

**Comment by gruppjo** [comment]
@nod. Good :) This will be default in the next version of the generator
