### ISSUE TITLE
vendor.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module puertasMagicas due to: Error: [$injector:nomod] Module 'puertasMagicas' is not available!

### ISSUE THREAD

**Issue by diegoalmesp** [mwaylabs/generator-m-ionic#357]
Hello, first of all, this is a great builder, congrats and thanks!!

now, to the error:

```
vendor.js:68 Uncaught Error: [$injector:modulerr] Failed to instantiate module puertasMagicas due to:
Error: [$injector:nomod] Module 'puertasMagicas' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```
this happends **only** when deploying on the android device, it doesn't happens on my local (Windows).

This module is the main module located in app.js
```javascript
'use strict';
angular.module('puertasMagicas', [
  // load your modules here
  'main',
  'games',
]);
```

If I check the app.js file inside /www I find that this declaration is at the end of it, so I moved it to the top, and now the app works perfect (checked this with "ionic serve").

I'm still new to Angular and this package, so: should I move the app.js tag to the top? if so, how or where should I edit so the app.js will be first in the index.html file (auto-generated)? Thanks in advance!

**Comment by diegoalmesp** [comment]
Found it!!! my mistake: I have a folder inside /assets that contains games in javascript, maybe some error in them was causing the problem, I should ignore this folder in the building and should be fine. Sorry for the reporting!

**Comment by gruppjo** [comment]
Thank you, Glad you found a solution :)
