### ISSUE TITLE
angular.module().run()

### ISSUE THREAD

**Issue by adyba** [mwaylabs/generator-m-ionic#360]
Would anybody help me to understand where and how is/should be processed `.run()` part of the application? The `generator-m-ionic-demo` seems to have no `.run()` part, which normally handles all the `$ionicPlatform` and `cordova plugins` (like StatusBar, Keyboard, etc.). When I use the `.run()` part the `jslint` spits out an 'not defined' errors which cancels all the build process. 
Its a bit `Catch22` coz before the app it is properly build `cordova` is not loaded and thus undefined by default.
```
C:\Users\***\ionic\****\app\app.js
  41:4  error    'cordova' is not defined      no-undef
  46:4  error    'cordova' is not defined      no-undef
  49:4  error    'StatusBar' is not defined    no-undef
 ```

Is it possible to separate the `.run()` part into a solo file which could be then blacklisted for `jslint`?
Thank you in advance.

**Comment by gruppjo** [comment]
Hi @adyba, this is not a runtime problem, this is a linting problem.
You can always force the build with `--force-build`.

But to solve your problem you simply need to add the globals you are using `cordova`, `Statusbar` to your `app/.eslintrc` like so:
```
"globals": {
    "angular": true,
    "ionic": true,
    "localforage": true,
    "cordova": true,
    "Statusbar": true
  }
```

although even better. Use the [ngCordova](http://ngcordova.com/docs/plugins/) services like `$cordovaDevice` and `$cordovaStatusbar` so you don't need the globals. Simply inject them into your run function.

**Comment by adyba** [comment]
Thank you

**Comment by gruppjo** [comment]
You're welcome. Did it help? :)
