### ISSUE TITLE
Extend config.js suffix

### ISSUE THREAD

**Issue by MakeSourceCode** [mwaylabs/generator-m-ionic#367]
Hi,

in the future release it would be useful to add the suffix keyword for service, template, directive and filter. (eg. CONTROLLER_SUFFIX: 'Ctrl' into utils/config.js file).

Thanks,

Lorenzo

**Comment by gruppjo** [comment]
Hi Lorenzo, I get that you would want to have some control over the naming conventions or even the general folder structure of your files. However we noticed that it takes a lot of time to make everything configurable and it brings a lot of edge cases without adding a real benefit as it's just a question of taste. 

Right now there's a lot of time-consuming tasks on the horizon like Typescript support and many other which have absolute priority.

So right now requests like these are not a priority. If you are willing to contribute and invest some work. I'll be happy to help you with a PR. I'm closing this for now, if you're interested just comment again.
