### ISSUE TITLE
Gulp cordova plugin install return 'add' not in gulpfile

### ISSUE THREAD

**Issue by 1moere1** [mwaylabs/generator-m-ionic#369]
gulp --cordova 'plugin add org.apache.cordova.camera --save'

Returns for me
Task 'add' is not in your gulpfile

With gulp --cordova "plugin add org.apache.cordova.camera --save" It works BUT only with the new Syntax:

gulp --cordova "plugin add cordova-plugin-camera --save"

New Syntax: https://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by gruppjo** [comment]
I suppose you are on windows? https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/windows.md

**Comment by gruppjo** [comment]
I guess that means yes :) Happy Coding!

**Comment by gruppjo** [comment]
Thanks for the reminder. Maybe it'll be good to have the docs regarding this issue platform-independent as well!
