### ISSUE TITLE
Usage of main.scss -> breaks styling of appliaction

### ISSUE THREAD

**Issue by 1moere1** [mwaylabs/generator-m-ionic#370]
when I add plain css into main.scss then the styling of my app breaks. How or where do I add correctly new stylings?

**Comment by gruppjo** [comment]
What css are you adding? What's the output of `gulp watch` when the styling breaks? Can you provide a screenshot?

**Comment by 1moere1** [comment]
During gulp watch I added this styling:
![image](https://cloud.githubusercontent.com/assets/9694983/15207747/4599a38c-1828-11e6-8ce1-583e05df8d9e.png)

I tried aswell by restarting gulp watch and had the same problem.

**Comment by gruppjo** [comment]
Please provide a repo that I can clone and the output of `gulp watch`

**Comment by 1moere1** [comment]
The problem got solved. gulp watch did not correctly compile the scss because const config got changed by gulp. i reverted the constant file while having gulp watch running and it worked.

**Comment by gruppjo** [comment]
Ok. Glad it worked. Please do a little more research before you open issues though!
