### ISSUE TITLE
'Ionic' not defined, 'ionic' in globals

### ISSUE THREAD

**Issue by nevace** [mwaylabs/generator-m-ionic#372]
I've just used the generator to install and get the eslint error Ionic not defined from lines 24 and 30 in user-ctrl.js..

```
Ionic.Auth.signup(this.user)

Ionic.Auth.login('basic', {'remember': true}, this.user)
```

Changing this to the below removes the error, presumably because of the eslintrc file

```
ionic.Auth.login('basic', {'remember': true}, this.user)
```

**Comment by gruppjo** [comment]
That's because `Ionic` is not part of the standard setup. You need to add it as the global to your `app/.eslintrc` file. More information on how to integrate the Ionic Platform is found in our [guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md).

**Comment by jackytse** [comment]
I got same error.

I tried this command:
```
$ yo m-ionic:ionic-platform
identical gulp/ionic.js
identical app/main/templates/user.html
identical app/main/controllers/user-ctrl.js
identical test/karma/main/user-ctrl.spec.js
```

**Comment by gruppjo** [comment]
The `.eslintrc` is case-sensitive! `ionic` and `Ionic` are two different globals, you need to register both of them!
