### ISSUE TITLE
non-issue: integrate sass after the fact

### ISSUE THREAD

**Issue by silentFred** [mwaylabs/generator-m-ionic#374]
Guys,

How do i integrate sass after scaffolding a new project after not picking sass or less? (my bad!)
I'm too far down to re-scaffold my project.

Any help would be much appreciated!

**Comment by MathiasTim** [comment]
Hey,

you can just rename your e.g. `main.css` file to `main.scss` and start `gulp watch` the gernerator should scann all `styles` directories and inject the complied css file into your `index.html`.

Please let me know If this helps.

**Comment by gruppjo** [comment]
There's a guide on how to change from using the Ionic's css to scss and vice versa: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/ionic_css_or_sass.md 
Does this work for you?

**Comment by silentFred** [comment]
This is actually what i was looking for: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/ionic_css_or_sass.md
