### ISSUE TITLE
comment include of cordova.js when using ionic platform

### ISSUE THREAD

**Issue by DEllingsworth** [mwaylabs/generator-m-ionic#375]
When using a base Ionic starter template and issuing the command:
`ionic add ionic-platform-web-client`

The index.html is changed to comment out the include of cordova.js. It results in this change:

```
    <!-- cordova script (this will be a 404 during development) -->
    <!-- Cordova is bootstrapped by ionic-platform-web-client, uncomment this if you remove ionic-platform-web-client... -->
    <!-- <script src="cordova.js"></script> -->
````

This change does not happen when using this file structure, so perhaps something could be in the docs to tell the user?

**Comment by gruppjo** [comment]
Would be very useful to mention that in this guide: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md
What do you think?

**Comment by DEllingsworth** [comment]
The other option would be to add it to the gulp ionic-platform command.  Perhaps that could modify the index.html directly.

**Comment by gruppjo** [comment]
I'm generally not a fan of modifying code programatically but in this case not so much can go wrong. I'll consider it. Thanks :)

**Comment by gruppjo** [comment]
Hi @DEllingsworth, I decided against doing this automatically since it breaks a build or run using `gulp --cordova` and that might lead to confusion. So I just mention it in the guide so everybody knows what's happening.
