### ISSUE TITLE
gulp --cordova no longer builds correct APK

### ISSUE THREAD

**Issue by mval1002** [mwaylabs/generator-m-ionic#376]
I would like to start by thanking you for releasing a great product! As a newbie to most of the technologies used it has helped a great deal with understanding them, and how they interact!

Recently, I have been having trouble with building the APK for testing. Everything was great, then seemingly overnight it was just a blank screen. (The title is shortened for readability - I do use the full command  [gulp --cordova "run android --device"]) After doing some digging, it seems as though it isn't building the correct index.html file. Inspecting the app through Chrome, there are dozens of "Failed to load resource: net::ERR_FILE_NOT_FOUND" errors - it's leaving the individual files and seems to be pointing to the wrong path for the compressed files.

I'm sure you'll need more information, but I don't know what that is. I truly don't know what I did wrong, and any help would be greatly appreciated!

**Comment by vineshhpatel** [comment]
Had same experience. Have you solved this issue?

**Comment by mval1002** [comment]
I have not

**Comment by vineshhpatel** [comment]
I updated my android build tools and platform sdks. This solved my issue.

**Comment by mval1002** [comment]
That did it! Thanks so much!

If you don't mind my asking, do you know why that would happen? I mean, if the older versions of the tools worked, why would an available update cause them to stop?

**Comment by gruppjo** [comment]
Hey guys good job on solving that issue for you and thank you for sharing your results! I'll close this issue since it's solved. Feel free to keep commenting!

**Comment by vineshhpatel** [comment]
@mval1002 Well, I am not android expert but most probable reason I think might be, with updated android versions in phones, we should also update our build tools and SDKs so it can generate a build that is runnable in latest android versions. 
I hope someone more experienced could comment and we can thank him/her. :)

**Comment by mval1002** [comment]
That would make sense, but at least in my case, there was no update on my phone or tablet. Both were already on Marshmallow before the issue started. The fact that updates to the Build Tools and SDK were simply available, with nothing else changing, seems to have caused the issue!
