### ISSUE TITLE
gulp: plugins for web-based apps

### ISSUE THREAD

**Issue by gruppjo** [mwaylabs/generator-m-ionic#39]
- gulp-ng-html2js - https://github.com/marklagendijk/gulp-ng-html2js
- gulp-angular-templatecache - https://github.com/miickel/gulp-angular-templatecache
- gulp-rev - https://github.com/sindresorhus/gulp-rev

**Comment by MathiasTim** [comment]
This could be interesting again, because we did some tablet apps, that should also run in the browser.
I will discuss this with the team and give feedback if we need something like this in the near future.

**Comment by gruppjo** [comment]
closed as discussed. We'll open a new issue for cache-busting with gulp-ref
