### ISSUE TITLE
editor/IDE ignores in .gitignore

### ISSUE THREAD

**Issue by gitbreaker222** [mwaylabs/generator-m-ionic#393]
JetBrains based IDEs like Webstorm (JS), Intelli-J (Java) and based on that Android Studio have an `.idea` directory. Though a android-studio-colleague told me only to ignore /.idea/workspace.xml*` and `/.idea/libraries`

Details on that for Intelli-J : http://stackoverflow.com/questions/26336709/android-studio-should-the-entire-idea-directory-be-in-git-ignore/26336926#26336926

...from the [Webstorm Docs](https://www.jetbrains.com/help/webstorm/2016.1/project.html?search=.idea):

> All the settings files in the .idea directory should be put under version control except the workspace.xml, which stores your local preferences. The workspace.xml file should be marked as ignored by VCS.

**Comment by MathiasTim** [comment]
I recommend using a global `.gitignore` more on that here: https://help.github.com/articles/ignoring-files/

**Comment by gruppjo** [comment]
Hi @MathiasTim! I agree with the practice of using a global `.gitignore`, nevertheless I think providing a local `.gitignore` configured for the most common IDEs might help beginners.

Speaking of VS Code, which files are recommended to be ignored for that?

**Comment by MathiasTim** [comment]
Sorry I can't completely agree to that. There are so many editors out there. (and people using a wide range of them). Maintaining all those is not something I want to do in a project.

Why not create a doc/faq for that?

**Comment by gruppjo** [comment]
@MathiasTim, I meant we just cover the most popular ones like VS Code, Atom, Sublime and Webstorm. As these are also the ones used at m-way?
As these are the ones we also cover in the [ESLint Guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/eslint.md)?

**Comment by gitbreaker222** [comment]
For the record: The list of IDE editors that would need to be supported (relevant for WebApp dev)

- Atom
- ~~Aptana Studio~~
- Brackets
- Light Table
- Slap
- Sublime
- VisualStudio Code
- Webstorm

On this List we can better estimate the work. Improving the list is welcome. I used alternativeto.net.

I would say, that more plain text editors like Kate, Gedit, Vim can be left out, as they don't provide code inspection and such features

**Comment by gruppjo** [comment]
I think 
- atom
- sublime
- vs code
- webstorm

would be enough. Never seen anybody use any of the others as a main editor.

**Comment by gitbreaker222** [comment]
one developer in the relution team uses brackets.

about webstorm: the ide initially puts `.idea/workspace.xml` on its own vcs ignore list, but this file shows up in `git status` as unversioned

**Comment by MathiasTim** [comment]
@gruppjo see (comment above), that what I mean. It's our perspective at this problem but can be very different in other companies and or countries.
As you can see in this survey [here] (http://angularjs.blogspot.de/2015/09/angular-2-survey-results.html) (scroll down to 'Editors') Many people using the common ones you described, but there are also 10% 'Others'.
The more editors you add the more people will complain.

**Comment by gitbreaker222** [comment]
@MathiasTim if we supported this 4 browsers (according to the survey 85,4% of all votes), how can we tell that the number of complains really will increase?

some experience to provide to the question: just now I added the recommended Webstorm IDE configs to the VCS on a new branch, switched back to master --> cannot switch to feature branch (with IDE), as these files would be overridden.

> local .gitignore configured for the most common IDEs might help beginners.

So if we want to help people to get into webapp development, in my eyes it would make sense to take it in, otherwise leave it out

**Comment by MathiasTim** [comment]
Just cam by another survey: https://ponyfoo.com/articles/javascript-developer-survey-results#what-are-your-preferred-text-editors, with much more 'other'.
