### ISSUE TITLE
problem with crosswalk

### ISSUE THREAD

**Issue by yailPeralta** [mwaylabs/generator-m-ionic#400]
I have installed crosswalk with the command gulp --cordova 'plugin add cordova-plugin-crosswalk-webview --save'  but when i want to build (emulate in android) i have   throw new TypeError('invalid data'); on /hooks/after_prepare/update_platform_config.js.
How integrate crosswalk and build using crosswalk with your generator?

**Comment by MathiasTim** [comment]
Hey @yailPeralta. We already got some apps with crosswalk working here @mwaylabs.

The problem with the cordova hook sounds familiar, but normally is when you add a platform that is not supported.
Can you please give us more information on that topic?
Node verison, cordova platform version (from your `config.xml`) and the complete stacktrace from the console would be great.

**Comment by yailPeralta** [comment]
Hi thanks for answer my question, I'm on Ubuntu 14.04, My node version is v5.8.0,  here is the entire config.xml file: `<?xml version='1.0' encoding='utf-8'?>
<widget id="com.test.yail" version="0.0.1" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
    <name>gem-m-ionic</name>
    <description>
        A sample Apache Cordova application that responds to the deviceready event.
    </description>
    <author email="dev@cordova.apache.org" href="http://cordova.io">
        Apache Cordova Team
    </author>
    <content src="index.html" />
    <plugin name="cordova-plugin-whitelist" spec="1" />
    <access origin="*" />
    <allow-navigation href="*" />
    <allow-intent href="http://*/*" />
    <allow-intent href="https://*/*" />
    <allow-intent href="tel:*" />
    <allow-intent href="sms:*" />
    <allow-intent href="mailto:*" />
    <allow-intent href="geo:*" />
    <platform name="android">
        <allow-intent href="market:*" />
    </platform>
    <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
    </platform>
    <engine name="android" spec="~5.1.1" />
    <plugin name="cordova-plugin-device" spec="~1.1.2" />
    <plugin name="cordova-plugin-dialogs" spec="~1.2.1" />
    <plugin name="cordova-plugin-inappbrowser" spec="~1.4.0" />
    <plugin name="cordova-plugin-network-information" spec="~1.2.1" />
    <plugin name="cordova-plugin-splashscreen" spec="~3.2.2" />
    <plugin name="cordova-plugin-x-toast" spec="~2.5.2" />
    <plugin name="cordova-plugin-geolocation" spec="~2.2.0" />
    <plugin name="cordova-plugin-media-capture" spec="~1.3.0" />
    <plugin name="com.wikitude.phonegap.WikitudePlugin" spec="https://github.com/Wikitude/wikitude-cordova-plugin.git" />
    <plugin name="ionic-plugin-keyboard" spec="~2.2.1" />
    <plugin name="cordova-plugin-image-picker" spec="https://github.com/wymsee/cordova-imagePicker.git" />
    <plugin name="com-badrit-base64" spec="https://github.com/hazemhagrass/phonegap-base64" />
    <plugin name="cordova-plugin-camera" spec="~2.2.0" />
    <preference name="xwalkVersion" value="19+" />
    <preference name="xwalkCommandLine" value="--disable-pull-to-refresh-effect" />
    <preference name="xwalkMode" value="embedded" />
    <preference name="xwalkMultipleApk" value="true" />
    <plugin name="cordova-plugin-crosswalk-webview" spec="~1.8.0" />
</widget>
`
and the complete log from console:

`[13:58:07] Starting 'cordova-with-build'...
Running command: /home/yailanderson/Documentos/IONIC_APPS/wikiSpot/hooks/after_prepare/update_platform_config.js /home/yailanderson/Documentos/IONIC_APPS/wikiSpot
net.js:623
    throw new TypeError('invalid data');
    ^

TypeError: invalid data
    at Socket.write (net.js:623:11)
    at /home/yailanderson/Documentos/IONIC_APPS/wikiSpot/hooks/after_prepare/update_platform_config.js:373:24
    at arrayEach (/home/yailanderson/Documentos/IONIC_APPS/wikiSpot/node_modules/lodash/lodash.js:451:11)
    at Function.forEach (/home/yailanderson/Documentos/IONIC_APPS/wikiSpot/node_modules/lodash/lodash.js:8634:14)
    at /home/yailanderson/Documentos/IONIC_APPS/wikiSpot/hooks/after_prepare/update_platform_config.js:368:7
    at Object.<anonymous> (/home/yailanderson/Documentos/IONIC_APPS/wikiSpot/hooks/after_prepare/update_platform_config.js:377:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
Error: Hook failed with error code 1: /home/yailanderson/Documentos/IONIC_APPS/wikiSpot/hooks/after_prepare/update_platform_config.js
[13:58:09] 'cordova-with-build' errored after 1.15 s
[13:58:09] Error in plugin 'gulp-shell'
Message:
    Command `node_modules/cordova/bin/cordova emulate android` failed with exit code 1
`

**Comment by yailPeralta** [comment]
I already fix the problem, you were right about the unsupported platform, I did not realize I had the added browser platform. Thank you!!

**Comment by MathiasTim** [comment]
@yailPeralta glad I could help!

@gruppjo we also had this problem some time ago. do you think we should refactor/improve the code to not fail when there is an unsupported platform? (e.g. windows, browser, etc.)

**Comment by yailPeralta** [comment]
@gruppjo Yes that could be better i think.

**Comment by gruppjo** [comment]
@MathiasTim, @yailPeralta, not sure if I understand. We could make the `gulp --cordova` commands suppress errors but the cordova command running within would still fail, which would create much more confusion. This way you at least know something's wrong, even when it's not really apparent *what*. Admittedly the errors are not really helpful but that's all we get from the Cordova CLI.

**Comment by yailPeralta** [comment]
@gruppjo I mean that in the case that i have a platform that isn't supported build anyway but log a message of warning.

**Comment by gruppjo** [comment]
@yailPeralta, everything's possible :) But in this case not with reasonable effort as this is just how the Cordova CLI behaves. I know that this can be confusing sometimes, but that behaviour should, if required, be requested in the Cordova CLI. Does that make sense?

Is it ok if close this issue?

**Comment by MathiasTim** [comment]
@gruppjo I think you don't understand the problem here. It's our very own hook (ok we took it from someone else) that is the problem here, not the `cordova-cli`.

**Comment by gruppjo** [comment]
@MathiasTim, sorry I was on a different train! I misread the initial issue and thought this the error produced by the cordova cli.

**Comment by gruppjo** [comment]
Closing because I don't see us updating that hook soon, especially since it only occurs on platforms that we don't support anyways. Feel free to comment if you disagree.
