### ISSUE TITLE
Support to use Greenhouse CI

### ISSUE THREAD

**Issue by volkrass** [mwaylabs/generator-m-ionic#405]
Greenhouse CI needs some prerequistes to be happy to compile Ionic Projects. http://docs.greenhouseci.com/docs/building-ionic-apps

One missing piece is that our generator is not creating an ionic.project file. 
Question should we provide this file to be compatible with the ionic cli? 
There are some more small changes necessary to compile sucessful our generator-m-projects.
We have to investigate first what we have to fix.

**Comment by gruppjo** [comment]
Did you integrate the Ionic CLI according to this guide? https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md That should create an ionic.project file.

**Comment by volkrass** [comment]
I create my ionic.project file by hand, but this is not enough to build the project with Greenhouse CI.
Can you investigate in this topic. I did send you an email, directly. Might be better to let us have an offsite discussion first.

**Comment by volkrass** [comment]
If you want build a generator-m-ionic project you can do it if you put following content in a file e.g. greenhouse-ci.sh and assign it to GH_POST_CLONE_SCRIPT environment variable.

Here is the script you need:

#!/bin/sh
# fail on first failed command
set -e
# install dependencies
echo -e '\n####################### INSTALL DEPENDENCIES #######################\n'
echo -e 'installing npm packages'
npm prune
npm install
echo -e 'installing bower packages'
bower prune
bower install
echo -e '\n#######################    CONFIGURATION     #######################\n'
# retrieve version from config.xml
VERSION="$(gulp config --silent --getWidgetAttr=version)"
# append the build number and save in config.xml
gulp config --setWidgetAttr="version=${VERSION}"
# set the android-versionCode
gulp config --setWidgetAttr="android-versionCode=${BUILD_NUMBER}"
gulp config --setWidgetAttr="android-versionName=${VERSION}.${BUILD_NUMBER}"
gulp config --silent --setWidgetAttr="ios-CFBundleVersion=${VERSION}.${BUILD_NUMBER}"
echo -e '\n#######################      GULP BUILD      #######################\n'
# run gulp build explicitly to make it more obvious what's happening
# build: inject version and build number into app
# build: with dev environment and minify
gulp build --buildVars="version:${VERSION},build:${BUILD_NUMBER}" --env=dev --minify

**Comment by volkrass** [comment]
@gruppjo, I would suggest to close this ticket for now.

**Comment by gruppjo** [comment]
@volkrass, let's talk about it!

**Comment by gruppjo** [comment]
done with #426
