### ISSUE TITLE
New Ionic Icon

### ISSUE THREAD

**Issue by rodrigograca31** [mwaylabs/generator-m-ionic#417]
The Ionic Icon is the only one without transparency... it looks ugly....

I wanted to contribute with a new one but did not understood where the images are hosted... https://cloud.githubusercontent.com/assets/1370779/6041296/59c5717a-ac7b-11e4-9d5d-9c5232aace64.png

I've found this logo with transparency: http://pixxstudios.com/wp-content/uploads/2015/04/ionic.twitter.sample-logo-4203547186-0_avatar.png

**Comment by gruppjo** [comment]
Hi @rodrigograca31, thanks! It usually is displayed with white background anyways so it hasn't been a problem for us. How are you viewing the `README.md` that you notice the missing transparency?

The logo you linked to, unfortunately is of insufficient resolution. For retina-displays we'll need a resolution at least ~230x190px like the original one: https://cloud.githubusercontent.com/assets/1370779/6041296/59c5717a-ac7b-11e4-9d5d-9c5232aace64.png

As for the upload. Just drag and drop the image in the `Write` section of a new comment here. It will upload it and generate a link for you.

**Comment by rodrigograca31** [comment]
Oh.... I have a theme installed for github ... I didn't even thought about that... Other people normally have a white background and don't even notice this.... 

I've found a logo that should work I will send a Pull Request with this one:

![ionic](https://cloud.githubusercontent.com/assets/1134310/17360098/b5975f2e-5961-11e6-8a13-70d258d35ffe.png)


FYI, My github looks like this:
(I'm using the `Stylish` Chrome extension.)

![page](https://cloud.githubusercontent.com/assets/1134310/17360055/7ead091e-5961-11e6-8961-cf693cb9d824.png)
