### ISSUE TITLE
support browser platform with livereload

### ISSUE THREAD

**Issue by nueko** [mwaylabs/generator-m-ionic#428]
Hi, I hope this feature is implemented here, thanks.

**Comment by gruppjo** [comment]
Hi, you can develop with livereload in your browser for development with `gulp watch` or on your device with `gulp --livereload 'run <platform>'` https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/development_intro.md#run-on-device-or-emulator-with-livereload

**Comment by nueko** [comment]
Yes i run gulp --cordova 'run browser' but must do that again when i edit the source, and for note, in the gulp --cordova 'run browser'  command we can use camera, geolocation, etc.

**Comment by gruppjo** [comment]
I understand what you mean now. We could try to get livereload work with the browser platform. Do you use the browser platform for testing or do you also use it for production?

**Comment by gruppjo** [comment]
@nueko. I got it implemented. See this commit (https://github.com/mwaylabs/generator-m-ionic/commit/a8eac57d4e3151eb592c0d6f16c2cf7a9cc723ae) if you want to use it right now or wait until the next release (probably some time next week)

**Comment by nueko** [comment]
Wow, thank for that.

Pada tanggal 1 Sep 2016 9.48 PM, "Jonathan Grupp" <notifications@github.com>
menulis:
