### ISSUE TITLE
Ionic Deploy update

### ISSUE THREAD

**Issue by Juliaandavid** [mwaylabs/generator-m-ionic#429]
Hi there,

In current week Ionic updated your platform Cloud, and the old version is deprecated for the apps.

Currently I have an issue and is the next:

`> ionic upload --note "Deploy 1"
Uploading app....
Saved app_id, writing to ionic.io.bundle.min.js...

Caught exception:
 TypeError: Can't call method on  undefined
    at TypeError (native)`

This happend of course, every time that I try to upload an deploy to Ionic.io.

**Comment by gruppjo** [comment]
Thanks for sharing your problem.
We're working on getting the ionic cloud integration to work. See this ticket #423.
