### ISSUE TITLE
Browserify

### ISSUE THREAD

**Issue by nueko** [mwaylabs/generator-m-ionic#431]
Hi, what about browserify?
I am sure have read all the docs, but couldn't found Browserify feature.

**Comment by gruppjo** [comment]
Hi @nueko, no plans currently to support browserify. We don't want to offer too many options and we figure if there's a good reason to use it and someone really needs it, they can get it to work themselves. If you want a guide on how to integrate it, we'll be happy to have a look at it and publish it. 

Additionally we have a version for angular 2 / ionic 2 in the pipeline but we're probably going to go with webpack.

**Comment by gruppjo** [comment]
Closing this as of above.
