### ISSUE TITLE
no html content load in emulator, when using livereload

### ISSUE THREAD

**Issue by gitbreaker222** [mwaylabs/generator-m-ionic#435]
I'm updating a project from 1.2 to latest generator 1.10. 

The app runs fine with 
`gulp --cordova "run ios --emulate --target='iPad-Air, 9.0"`
 but not with
`gulp --livereload "run ios --emulate --target='iPad-Air, 9.0'"`

The emulator starts the app but only shows an empty canvas (a splashscreen, if exists) - in Safari dev tools the markup is only an empty header and body.

Here is an emoji of a snake - the symbol of knowledge: 🐍

**Comment by gruppjo** [comment]
Please contact me directly with a repo I can clone if this problem still persists!
