### ISSUE TITLE
Environment specific settings in config.xml

### ISSUE THREAD

**Issue by asgeo1** [mwaylabs/generator-m-ionic#437]
I've seen a few cordova plugins now, which require that API keys and such to be configured in `config.xml`

For example, I'm using intercom-cordova plugin, and have to set the API keys like so in `config.xml`:

```
<preference name="intercom-app-id" value="..."/>
<preference name="intercom-ios-api-key" value="ios_sdk-..."/>
<preference name="intercom-android-api-key" value="android_sdk-..."/>
<preference name="intercom-android-sender-id" value="..."/>
```

Sadly, because it's hard-coded in config.xml, I have no way of switching between my test and production Intercom accounts when I run the `gulp build` commands.

You could argue that the intercom-cordova plugin should allow these things to be set via Javascript, but apparently they have a reason why it can't be done that way, and must be done when the app boots.   So they have to use config.xml to set these values.

Anyway... Does anyone else have this issue?

I like that the `gulp config` command can change _some_ of the fields in the config.xml programatically.  I.e. the appId, and the versionNo etc.

But it doesn't seem possible currently to change the `<preference>` tags yet.

If that were possible, then that would probably solve this issue for me.   Is that something that could be added?

Or are there any other ways to deal with this?

**Comment by gruppjo** [comment]
Hi @asgeo1, we're currently not working on anything similar. The implementation of `gulp config` can be found here: https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/gulp/configuring.js#L12. It uses the [node-xml2js](https://github.com/Leonidas-from-XIV/node-xml2js) package.

You can try to add options like `--addPreference` and `--removePreference` yourself. If you have a working solution I'd be very happy to help you make a PR, so it can become an integrated, maintained feature in generator-m-ionic.

**Comment by asgeo1** [comment]
@gruppjo, OK I'll have a look into it.

I've been thinking though, and I like the approach I saw here:  https://github.com/theodo/gulp-ionic-channels

Where the config.xml is generated via a template.

So any of the environment variables in "config.json" (or `env-*.json` as per this generator), can be injected into the config.xml file.

I think I like that approach better, because the configuration then is just in one place, and can be used through out the whole app.

Yes, it would mean some of the `cordova` commands which manipulate the config.xml file, you would then have to manually apply the same change to the template, but don't think that is a huge deal.

What do you think?

**Comment by gruppjo** [comment]
@asgeo1, let me know how everything is going with this. Was not aware of `gulp-ionic-channels`. If I find some time I'll have a look at it. Sounds interesting.

**Comment by DrMabuse23** [comment]
👍

**Comment by gruppjo** [comment]
I'm closing this, due to inactivity. If there's strong interest, I'm happy to discuss PR details

**Comment by rameshkatare9** [comment]
**gulpfile.js**
  const gulp = require('gulp');
const Config = require('cordova-config');
var fs = require('fs');
var argv = require('yargs').argv;

gulp.task('config', function () {

    let data;
    let env = argv.channelTag;
    if (!env || env === 'dev') {
        data = fs.readFileSync('src/environments/environment.ts', 'utf-8');
    } else {
        data = fs.readFileSync('src/environments/environment.' + env + '.ts', 'utf-8');
    }

    let startIndex = data.indexOf("{");
    let lastIndex = (data.indexOf("}")) + 1;

    let configEnv = JSON.parse(data.substring(startIndex, lastIndex));
    console.log(configEnv);

    const configXml = new Config('config.xml');

    configXml.setID(configEnv.appId);
    configXml.setName(configEnv.appName);
    configXml.setVersion(configEnv.version);
    configXml.setAndroidVersionCode(configEnv.versionCode);


    // Write the config file
    configXml.writeSync();
});

**environment.ts**
 export const environment = {
  "production": false,
  "appId": "in.xyz.abcDev",
  "appName": "MyApp Dev",
  "version": "0.0.1",
  "versionCode": "1000"
};

**Comment by rameshkatare9** [comment]
**gulpfile.js**

const gulp = require('gulp');
const Config = require('cordova-config');
var fs = require('fs');
var argv = require('yargs').argv;

gulp.task('config', function () {

let data;
let env = argv.channelTag;
if (!env || env === 'dev') {
    data = fs.readFileSync('src/environments/environment.ts', 'utf-8');
} else {
    data = fs.readFileSync('src/environments/environment.' + env + '.ts', 'utf-8');
}

let startIndex = data.indexOf("{");
let lastIndex = (data.indexOf("}")) + 1;

let configEnv = JSON.parse(data.substring(startIndex, lastIndex));
console.log(configEnv);

const configXml = new Config('config.xml');

configXml.setID(configEnv.appId);
configXml.setName(configEnv.appName);
configXml.setVersion(configEnv.version);
configXml.setAndroidVersionCode(configEnv.versionCode);


// Write the config file
configXml.writeSync();
});

**environment.ts**

export const environment = {
"production": false,
"appId": "in.xyz.abcDev",
"appName": "MyApp Dev",
"version": "0.0.1",
"versionCode": "1000"
};

**Use Below command to generate config.xml**
gulp config --channelTag=<dev/uat/prod>
