### ISSUE TITLE
Karma/Phantom tests not supporting es6

### ISSUE THREAD

**Issue by adolfosrs** [mwaylabs/generator-m-ionic#438]
I'm being able to use es6 to my ionic project but I can't test code written with es6 when running `gulp karma`. I've tried installing `karma-es6-shim` hopping that it would do the trick but was not effective.

When testing a arrow function I'm getting:

```
PhantomJS 2.1.1 (Mac OS X 0.0.0) ERROR
  SyntaxError: Unexpected token '>'
  at app/main/services/list-serv.js:36

```

Does anyone run through the same problem?

**Comment by gruppjo** [comment]
Hi @adolfosrs, you could check out other setups for karma using ES6 and then adapt the `karma.conf.js` https://github.com/mwaylabs/generator-m-ionic/blob/master/generators/app/templates/karma.conf.js.

It shouldn't be too hard I think! Let me know if you find something :)

**Comment by fedorinoGore** [comment]
Hi @adolfosrs ! Trust you doing well and in a good health. Could you please share some source code to see how you added ES6 support for this boilerplate?

**Comment by jairemix** [comment]
I've added ES6 support to the boilerplate produced by this Yeoman generator. It's working for Karma, ESLint and gulp build. The only more work left is to add support for ES6 imports (which based on my understanding needs Browserify and Babelify).

As for fixing the error with Karma, you'll need to add install "karma-babel-preprocessor" through node and the following piece of code to your karma.conf.js file:

    preprocessors: {
      'app/**/templates/**/*.html': ['ng-html2js'],
      'app/!(bower_components)/**/*.js': ['babel'],
      'test/karma/**/*.js': ['babel']
    },
    babelPreprocessor: {
      options: {
        presets: ['es2015'],
        sourceMap: 'inline'
      },
      filename: function (file) {
        return file.originalPath.replace(/\.js$/, '.es5.js');
      },
      sourceFileName: function (file) {
        return file.originalPath;
      }
    },

You can also have a look at how I set everything up in my project here: https://github.com/jairemix/ionic1-es6-starter

**Comment by gruppjo** [comment]
Inactive.
