### ISSUE TITLE
Generator-M 1.10 says it's generating a 1.9.2 project

### ISSUE THREAD

**Issue by funkybaboon** [mwaylabs/generator-m-ionic#439]
![alt text](http://i.imgur.com/5QQgqxi.png "Logo Title Text 1")

**Comment by gruppjo** [comment]
This looks like a problem with your setup? Did you use `--global` when `npm install`ing? Are you using nvm?

**Comment by funkybaboon** [comment]
Problem was nvm. This worked:

> 33731  2016-09-30 15:35:37 nvm use system
33732  2016-09-30 15:35:59 sudo npm uninstall yo -g
33733  2016-09-30 15:36:14 nvm use 6
33734  2016-09-30 15:36:19 npm i yo -g
33735  2016-09-30 15:36:45 npm i -g generator-m-ionic

**Comment by gruppjo** [comment]
Great!
