### ISSUE TITLE
How can I see console logs when running -  gulp --livereload "run android"?

### ISSUE THREAD

**Issue by nirber** [mwaylabs/generator-m-ionic#440]
Is there a way to print the logs in the CLI (like "ionic run android -l -c" )?

**Comment by gruppjo** [comment]
Hi @nirber. No. But you can inspect with safari or chrome for iOS and Android apps respectively and read the logs there!

**Comment by nirber** [comment]
Thanks @gruppjo , how is that work?

**Comment by gruppjo** [comment]
Check out this guide:
http://developer.telerik.com/featured/a-concise-guide-to-remote-debugging-on-ios-android-and-windows-phone/
Or this one: 
https://developers.google.com/web/tools/chrome-devtools/remote-debugging/
