### ISSUE TITLE
Inject SCSS at build time?

### ISSUE THREAD

**Issue by zachlyon** [mwaylabs/generator-m-ionic#441]
I'm looking for a recommended method to dynamically specify a stylesheet at build time, for example, A/B design testing for themes.

Much like toggling with  ` gulp build --env=X ` or ` gulp build --res=X ` which are both fantastic time savers, I'm looking for something like ` gulp build --theme=X ` or ` gulp build --sass=X `

I was thinking of having files "main/styles/themes/_themeA.scss" and "main/styles/themes/_themeB.scss" or similar. Then either run that through `gulp sass` or inject into index.html?

Or, could/should this be done with BuildVars?

**Comment by gruppjo** [comment]
@zachlyon, I'd recommend you take a look at the `styles` task in the gulp files.
https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/gulp/injecting.js#L36

You could modify it to take any command line argument and alter it's behaviour according to the value. Similiar to these tasks: 
https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/gulp/injecting.js#L114
https://github.com/mwaylabs/generator-m-ionic-demo/blob/master/gulp/building.js#L39

Let us know how you're doing!
