### ISSUE TITLE
Splash screen is not generated. No all Icons are generated for all devices sizes

### ISSUE THREAD

**Issue by MikelArnaiz** [mwaylabs/generator-m-ionic#444]
I having issues to generate the icons and splash screen.

[With ionic CLI](http://ionicframework.com/docs/cli/icon-splashscreen.html) that is quite simple.
`ionic resources --icon`
`ionic resources --splash`

It resizes the icon to the different device sizes, and [adds paths in config.xml](https://gist.github.com/MikelArnaiz/51b4dbfb450e957400b539afb744144e).
In m-ionic [the guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/icons_splash_screens.md) says we have to do it ourselves, in my opinion it should not.

Docs also says splash screen will be generate with any command like;

> [...] And run any of the cordova build related commands (`cordova run`, `build`, `emulate`, `serve`, `prepare`) [...]

But it does not, even I added `<splash src="res/android/default/screen.png" />` in config.xml. I could not make it work with a splash screen.

I saw m-ionic does not generate icon/splash screen for different devices. Is not this an issue?
![screen shot 2016-10-25 at 16 14 10](https://cloud.githubusercontent.com/assets/2076221/19689693/7cf184ca-9ace-11e6-8a83-c8ee4ba7a2ea.png)

As I said `ionic resources` worked quite well but I am not able to use it as it does not have a ionic.config.json file.

> Mikels-iMac:m-ionic-test-resources mikel$ ionic resources
> Couldn't find ionic.config.json file. Are you in an Ionic project?

I have this issue and I tested in a clean project; yo m-ionic, tabs template.
Enviroment: 
- OS X El Capitan; 10.11.5
- Node: v5.6.0
- NPM: 3.9.6
- npm list -g generator-m-ionic: generator-m-ionic@1.10.0
- gulp --cordova ' -v': 6.3.1

**Comment by gruppjo** [comment]
Hi @MikelArnaiz. Generator-M-Ionic is not designed to work with any of the `ionic` commands. However we support working with the `ionic cloud` which is discussed in more detail in the [Ionic Cloud Integration Guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/ecosystems/ionic_platform.md) which you can find in our docs. In order to configure your generator-m-ionic project with splash screens and app icons check out that guide too: [Icons and splash screens](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/icons_splash_screens.md). It extends the mechanisms Cordova provides to add these assets to your app.

We thought about integrating the `ionic resources` command as well, but the ionic CLI doesn't allow that at this time.

I recommend to learn the Cordova way to do it. You can still use `ionic resources` command to generate your files, but you'll have to add them to the `config.xml` manually, for now.

**Comment by capitola-dev** [comment]
You can try yourself:

1. `yo m-ionic`. Answer the questions. Choose tabs template.
2. Move [icon](http://imgur.com/1KhW4fc) and[ splash screen](http://imgur.com/qWR3CUI) images to res/android/default folder.
3. In config.xml file, inside `<platform name="android">` tag add the following:

    `<icon src="res/android/default/icon.png" />`
    `<splash src="res/android/default/screen.png" />` (BTW **not mentioned in the docs**)
4. Run `gulp --cordova "run android"`

App is installed but it crash (Samsung Galaxy S6). Icon image is 1024x1024px, splash screen is 2208x2208px [as ionic says](http://ionicframework.com/docs/cli/icon-splashscreen.html). Could be as m-ionic does't resize them it is too big for android. If icon image MB size is big it crash too.

![screenshot_20161027-115411 copy](https://cloud.githubusercontent.com/assets/22960845/19764558/cfa53538-9c43-11e6-926c-74540914a869.png)

Besides.

> You can still use ionic resources command to generate your files, but you'll have to add them to the config.xml manually, for now.

Are you proposing the following? 

1. Create somewhere else an ionic CLI project, e.g `ionic start myApp tabs`
2. Create resources directory
3. Move [icon](http://imgur.com/1KhW4fc) and[ splash screen](http://imgur.com/qWR3CUI) images there
4. `run ionic resources android`
5. Copy the produced `resources/android` folder into my m-ionic project root.
6. Copy `<platform name="android">` tag from ionic config.xml to m-ionic project config.xml.

Alright, this works, but isn't to tedious? Mainly if you need to change the resources frequently.

Cheers,
Mikel

**Comment by gruppjo** [comment]
As I said, this is out of scope of the generator.

>  Could be as m-ionic does't resize them it is too big for android

You'll have to make sure yourself these images are the correct sizes as mentioned in the cordova documentations: http://cordova.apache.org/docs/en/latest/reference/cordova-plugin-splashscreen/index.html http://cordova.apache.org/docs/en/latest/config_ref/images.html which we refer to in our guide.

**Comment by capitola-dev** [comment]
I understand. 

I will check if I can make it work with [cordova-splash](https://github.com/AlexDisler/cordova-splash) and [cordova-icon](https://github.com/AlexDisler/cordova-icon)
