### ISSUE TITLE
Folder structure

### ISSUE THREAD

**Issue by vjoao** [mwaylabs/generator-m-ionic#447]
If this generator is self entitled "A rock-solid foundation to build mobile apps" them why is the folder structure so poor? Dividing the project by file type is a bad practice for large projects. 
Why don't you make the project divided by feature instead?

**Comment by gruppjo** [comment]
More information is here: https://github.com/mwaylabs/generator-m-ionic/issues/289

TL;DR - We see the point. The folder structure originates from a time where none of the guidelines were established. It's historically grown but now we're investing our time in a version for angular 2 / ionic 2 adhering to the guidelines.
