### ISSUE TITLE
Support for ES6 syntax

### ISSUE THREAD

**Issue by fedorinoGore** [mwaylabs/generator-m-ionic#449]
I just found out that this beautiful and shiny boilerplate does not support ES6. 
Accidentally figured this out while seeing `gulp-angular-filesort ` errors on arrow functions in source code.
The problem is that the project is already in development and I don't want to change horses on the ride. And I like this boiler. It is made with love.
Maybe any receipts available on how to safely add ES6-ES5 transpiling to this boilerplate?
It is almost 2017 so using ES5 instead of ES6 looks like a real issue to me...

**Comment by gruppjo** [comment]
Hi @fedorinoGore, we're currently working a version for angular2/ionic2 so there's currently no budget for large feature tasks like this one.

If you're interested in getting some work done on this I'm happy to help you with a PR.

**Comment by gruppjo** [comment]
Inactive.
