### ISSUE TITLE
Gulp inject-all stops

### ISSUE THREAD

**Issue by tangorri** [mwaylabs/generator-m-ionic#451]
Suddenly I can't watch my project.

`gulp inject-all`

gives

```
Using gulpfile ~\Documents\Clients\greenroom\tips\tips-front-generator-m-ionic\gulpfile.js
Starting 'clean'...
Starting 'wiredep'...
Starting 'bower-fonts'...
Starting 'environment'...
gulp-inject 1 files into main\constants\config-const.js.
Finished 'clean' after 178 ms
Starting 'styles'...
Finished 'wiredep' after 584 ms
Finished 'environment' after 546 ms
Starting 'build-vars'...
gulp-inject Nothing to inject into main\constants\config-const.js.
Finished 'build-vars' after 54 ms
Finished 'styles' after 471 ms
Finished 'bower-fonts' after 640 ms
Starting 'inject-all'...
```

And that's all, return to shell.
I know the blocking part is 

gulp/injecting.js the task itself. On line 16 if replaced with return true it follows ...
Do not know, even after searching on the web, how to get more verbose infos...

EDIT: more precisely it comes from 

// .pipe($.plumber()) // use plumber so watch can start despite js errors
// .pipe($.naturalSort())
// .pipe($.angularFilesort())

I'll will ask there then maybe.

**Comment by gruppjo** [comment]
@tangorri. If you provide a repo I can clone I could help track down the problem more easily.

**Comment by tangorri** [comment]
Can't reproduce the issue, moved to ionic2 btw

**Comment by gruppjo** [comment]
Thanks for letting us know!

**Comment by sudheerDev** [comment]
I am running into this issue!!
