### ISSUE TITLE
Change port for Gulp serve

### ISSUE THREAD

**Issue by ksgupta-adobe** [mwaylabs/generator-m-ionic#461]
Hi,

As  I understand, the generator gulp serve task takes the gulp defaults for loading and watching the build. to change the port and other settings in gulp, one can change them in the ./gulp/server.js file, which is not poart of the app generator generates.  Are these settings done in some other config for the generated app or shall one be creating own server.js file as per gulp guidelines.

Please suggest.

**Comment by jairemix** [comment]
In the file gulp/watching.js, where it's defining Browsersync options, add the port number of your choice:

` 
var bsOptions = {
    server: {
      baseDir: paths
    },
    port: 3000
};
`

**Comment by gruppjo** [comment]
Hi @jairemix. Thank you for jumping in and helping out. @ksgupta-adobe, I'll close this issue then. Feel free to comment again if there's more you need help with.
