### ISSUE TITLE
Update cordova?

### ISSUE THREAD

**Issue by suscodev** [mwaylabs/generator-m-ionic#463]
I'm trying to update the version of cordova installed with the app, but nothing seems to touch it. I've found this same question in various other issues but they're all closed without any specific solution proffered. How do I do this?

**Comment by gruppjo** [comment]
Hi @suscodev,
I'm not sure I exactly understand what you mean. You should just be able to update the cordova dependency in the devDependencies of the `package.json` and reinstall. What other issues are you talking about?

For instance:
```json
"cordova": "6.4.0"
```

**Comment by gruppjo** [comment]
feel free to comment if you still have troubles with the cordova version
