### ISSUE TITLE
Use npm scripts as alias

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#466]
We could use [npm scripts](https://docs.npmjs.com/misc/scripts#examples) for "complicated commands"

e.g.

```
gulp --cordova 'run ios --buildConfig=build.json --device' --env=dev --res=dev
```

could be

```
npm run run-ios-device
```

Don't know if its just something we could write in a guide or preconfigure for some commands in the generated project.

What do you think @lordgreg @gruppjo ?

**Comment by gruppjo** [comment]
@MathiasTim, I really like the idea of supplying a default set of commands via npm scripts. Additionally, we might as well provide a guide on what they do and how to configure them. 

Thank might actually clarify some the main workflows of the generator for beginners and clear up any initial confusion of how certain things are done.

Really good idea 👍

**Comment by gruppjo** [comment]
@MathiasTim, one of the many great things about this is: you can make your common flags part of the command.

For instance `--no-open` for `gulp watch`.
![image](https://cloud.githubusercontent.com/assets/1370779/23067859/6a3382c2-f521-11e6-9240-13decf669b8b.png)
```
npm start
```
And you're done.

This might make our `gulp defaults` task and setup obsolete. 

I like this idea so much. I'm actually a little jealous that I didn't think of this! :)

**Comment by gruppjo** [comment]
This will also make it a lot easier to distribute **best practices** and avoid **common pitfalls** when running cordova commands for instance.

Additionally a guide would make sense, I think. To configure the default script using for instance `--target` and other flags: https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/development_intro.md#build-on-a-deviceemulator

However, we need to be aware that it will be perceived as **our responsibility** by the users that these commands will work. We're adding another layer of complexity and some might not even care that we're using gulp, cordova and all that underneath...

**Comment by gruppjo** [comment]
This would be my initial suggestion:
```js
"scripts": {
    "test": "npm run build && gulp karma",
    "start": "gulp watch",
    "watch": "npm start",
    "prepare": "gulp --cordova 'prepare'",
    "livereload:ios": "gulp --livereload 'run ios'",
    "livereload:android": "gulp --livereload 'run android'",
    "run:ios": "gulp --cordova 'run ios --buildConfig=build.json'",
    "run:android": "gulp --cordova 'run android'",
    "watch:build": "gulp watch-build",
    "build": "gulp build --minify"
  }
```
@MathiasTim, @lordgreg. Comments?

**Comment by MathiasTim** [comment]
From my perspective this is a good start.

**Comment by lordgreg** [comment]
I'd wait through weekend. Maybe we could think of more of the commands.

🥇

**Comment by gruppjo** [comment]
docs, how to use options:
```sh
npm run watch -- --env=prod
```
