### ISSUE TITLE
Add Cache-Busting

### ISSUE THREAD

**Issue by MathiasTim** [mwaylabs/generator-m-ionic#474]
Sometimes we use the generator to create web projects with no cordova container.
Therefore we have some issues with browser caching.

Summary: https://css-tricks.com/strategies-for-cache-busting-css/

Maybe use this library? https://github.com/sindresorhus/gulp-rev

**Comment by lordgreg** [comment]
@MathiasTim 

`Cachebusting` implementation has been implemented. [PR](https://github.com/mwaylabs/generator-m-ionic/pull/483) has been submitted and awaiting response from @gruppjo.

_Grab a 🍔 , wait for the implementation to appear in master branch 👍 _
