### ISSUE TITLE
Improve Sass task to inject css file

### ISSUE THREAD

**Issue by CornejoReyes** [mwaylabs/generator-m-ionic#501]
During a long development, reloading app only for CSS files becomes a little stressful, so, modify gulp task as an improvement to only inject css files and not reload the whole app is kind better.

`watching.js` file:
```
gulp.watch(paths.cssFiles, function () {
    return gulp
    .src(paths.cssFiles)
    .pipe(bs.stream());
  });
```

**Comment by MathiasTim** [comment]
Hey there, 
thanks for the hint, but I think the newest version [1.11](https://github.com/mwaylabs/generator-m-ionic/releases/tag/1.11.0) already has that feature.

Was merged with this PR: https://github.com/mwaylabs/generator-m-ionic/pull/462/files

**Comment by CornejoReyes** [comment]
Sorry, don't know about it.
Regards!

**Comment by MathiasTim** [comment]
You are welcome :)
