### ISSUE TITLE
getting problem with building apk file

### ISSUE THREAD

**Issue by pavan2540** [mwaylabs/generator-m-ionic#503]
the index.html file is in app folder and when i building the apk its looking in to the www/index.html file ,

how to change root document directory , we can able to generate apk outside www folder

**Comment by MathiasTim** [comment]
Changing the root folder shouldn't be the solution to your problem.
I guess you haven't build the javascript part before with `gulp build` ?

Other questions are, how are you building the apk?
Have you read [the Guide](https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/development_intro.md#using-the-cordova-cli) about using cordova with this generator?

**Comment by pavan2540** [comment]
I did the build now, but im getting the following error. As of now i do not have any additional cordova plugin installed. Just want to build the default html/js pages and view them on an emulator. 

`[22:47:15] Finished 'build' after 204 ms
[22:47:15] Starting 'cordova-with-build'...
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn node_modules\cordova\bin\cordova run android ENOENT
    at exports._errnoException (util.js:907:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
`

**Comment by MathiasTim** [comment]
Could be the same Error as #500.

I think its an issue with cordova and a node version before 6.x
Can you confirm this?

**Comment by pavan2540** [comment]
Hi Mathias ,  problem was same with older version of node , after installing latest node & reinstalling node modules  ,the  issue resolved.
 Thank's for the replay
