### ISSUE TITLE
How install font-awesome?!

### ISSUE THREAD

**Issue by tiagoSAmaral** [mwaylabs/generator-m-ionic#532]
I tryed install font-awesome without success... 
 i do this solution, [https://github.com/mwaylabs/generator-m-ionic/issues/330](url), but This only works in web server `gulp watch`, when use in real device with command `gulp --cordova "run android"`, not work.

![network error](https://user-images.githubusercontent.com/3158966/33568083-62a6d8e0-d90c-11e7-89e2-d27698ff46f8.png)

Path inside device:

![path](https://user-images.githubusercontent.com/3158966/33568291-229bbbd4-d90d-11e7-9558-8631493a8208.png)

Folder www/fonts after build/run android
![www-fonts-after-run-android](https://user-images.githubusercontent.com/3158966/33568365-57febd62-d90d-11e7-8888-067f7803b0f2.png)

i maked a console.log in gulp / injection.js file, in 'bower-fonts' task, i noticed that fontFiles has only this fonts paths:

![finded-fonts](https://user-images.githubusercontent.com/3158966/33569329-6b0355f0-d910-11e7-9bfd-da0052da2d26.png)

**Comment by glats** [comment]
Same here! Any advices?

**Comment by glats** [comment]
Adding `.concat('app/bower_components/font-awesome/fonts/**/*');` in `bower-fonts` gulp task like this:

```
gulp.task('bower-fonts', function () {
  // to app/main/assets/fonts (path can be set in app/main/styles/<module>.scss)
  var DEST = 'app/main/assets/fonts';
  var fontFiles = mainBowerFiles({filter: /\.(eot|otf|svg|ttf|woff|woff2)$/i})
    .concat('app/main/assets/fonts/**/*')
    .concat('app/bower_components/font-awesome/fonts/**/*');

  return gulp.src(fontFiles)
    .pipe($.changed(DEST))
    .pipe(gulp.dest(DEST));
});
```

then run `gulp inject-all` and finally `gulp buid`

**Comment by glats** [comment]
add this to bower.json:
```
  "overrides": {
    "font-awesome": {
      "main": [
        "less/font-awesome.less",
        "scss/font-awesome.scss",
        "fonts/FontAwesome.otf",
        "fonts/fontawesome-webfont.eot",
        "fonts/fontawesome-webfont.ttf",
        "fonts/fontawesome-webfont.woff",
        "fonts/fontawesome-webfont.woff2"
      ]
    }
  }
```

**Comment by tiagoSAmaral** [comment]
This copy files to www/fonts/... folder, but don't works. This generator, don't has  a main.scss file in project...

**Comment by tiagoSAmaral** [comment]
SOLUTION: 

 First change the Ionic Style Source : 
https://github.com/mwaylabs/generator-m-ionic/blob/master/docs/guides/ionic_style_source.md

After this change, create a main.scss and import the Ionic-icons, ionic scss and finally font-awesome.

Like this: 

```
// <my-main-module/folder>/main.scss 

$fa-font-path: "<path-to>/fonts" !default;
$ionicons-font-path: "<path-to>/fonts" !default;
@import "../../bower_components/ionic/scss/ionic";
@import "../../bower_components/font-awesome/scss/font-awesome";
```

This works for me in ionic server and build/run in real device (Android)
